"""gSage AI — Elasticsearch async client for the elk_search tool.

Thin wrapper around ``elasticsearch.AsyncElasticsearch`` targeted at
**external** ELK clusters (logstash/beats stacks).  Independent from
:mod:`src.shared.elasticsearch.client`, which talks to the gSage internal
cluster — the two must never share a connection, configuration, or
credentials.

Authentication: API key only (Base64 id:secret, as generated by Kibana
``Stack Management → API keys``).  Username/password is intentionally out
of scope for V1.
"""

from __future__ import annotations

import logging
import ssl
from types import TracebackType
from typing import Any, Optional

from elasticsearch import (
    ApiError,
    AsyncElasticsearch,
    AuthenticationException,
    AuthorizationException,
    ConnectionError as EsConnectionError,
    ConnectionTimeout,
    NotFoundError,
    TransportError,
)

log = logging.getLogger(__name__)


class ElkError(Exception):
    """Raised for all ELK client errors (auth, network, API)."""

    def __init__(
        self,
        message: str,
        code: str = "ELK_ERROR",
        retryable: bool = False,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.retryable = retryable


class ElkClient:
    """Async Elasticsearch client for external ELK clusters.

    Parameters
    ----------
    url:
        Cluster URL (e.g. ``https://elk.example.com:9200``).
    api_key:
        Base64 API key (``id:secret``) as issued by Kibana.
    verify_ssl:
        Whether to verify the server TLS certificate (default: ``True``).
    ca_cert:
        Optional path to a PEM-encoded CA bundle used to validate the
        server certificate.  Ignored when ``verify_ssl`` is ``False``.
    timeout:
        Request timeout in seconds (default: 30).
    """

    def __init__(
        self,
        url: str,
        api_key: Optional[str] = None,
        verify_ssl: bool = True,
        ca_cert: Optional[str] = None,
        timeout: int = 30,
    ) -> None:
        if not url:
            raise ElkError("Elasticsearch URL is required.", code="INVALID_CONFIG")

        self._url = url.rstrip("/")
        self._api_key = api_key or None
        self._verify_ssl = verify_ssl
        self._ca_cert = ca_cert or None
        self._timeout = timeout
        self._client: Optional[AsyncElasticsearch] = None

    # ── Context manager protocol ────────────────────────────────────────

    async def __aenter__(self) -> "ElkClient":
        ssl_ctx: Optional[ssl.SSLContext] = None
        if self._verify_ssl and self._ca_cert:
            ssl_ctx = ssl.create_default_context(cafile=self._ca_cert)

        kwargs: dict[str, Any] = {
            "hosts": [self._url],
            "request_timeout": self._timeout,
            "verify_certs": self._verify_ssl,
            "retry_on_timeout": True,
            "max_retries": 2,
        }
        if self._api_key:
            kwargs["api_key"] = self._api_key
        if ssl_ctx is not None:
            kwargs["ssl_context"] = ssl_ctx
        elif not self._verify_ssl:
            # Explicitly disable hostname check too; otherwise the client
            # still validates hostname against the server certificate.
            kwargs["ssl_show_warn"] = False

        self._client = AsyncElasticsearch(**kwargs)
        return self

    async def __aexit__(
        self,
        exc_type: Optional[type[BaseException]],
        exc: Optional[BaseException],
        tb: Optional[TracebackType],
    ) -> None:
        if self._client is not None:
            try:
                await self._client.close()
            except Exception:
                log.debug("elk_search: error closing AsyncElasticsearch", exc_info=True)
            self._client = None

    # ── Public operations ───────────────────────────────────────────────

    async def list_indices_raw(self) -> list[dict]:
        """Return the raw ``_cat/indices`` response as a list of dicts.

        Output fields (subset): ``index``, ``docs.count``, ``store.size``,
        ``creation.date.string``.
        """
        try:
            resp = await self._require_client().cat.indices(
                format="json",
                bytes="b",
                h="index,docs.count,store.size,creation.date.string",
                s="index",
            )
        except Exception as exc:
            raise self._translate_error(exc) from exc

        body = resp.body if hasattr(resp, "body") else resp
        rows: list[dict] = []
        for item in body or []:
            if isinstance(item, dict):
                rows.append(item)
        return rows

    async def get_mapping(self, pattern: str) -> dict:
        """Return the raw ``_mapping`` response for *pattern*.

        Raises :class:`ElkError` if no index matches.
        """
        try:
            resp = await self._require_client().indices.get_mapping(index=pattern)
        except Exception as exc:
            raise self._translate_error(exc) from exc

        body = resp.body if hasattr(resp, "body") else resp
        if not body:
            raise ElkError(
                f"No indices match pattern '{pattern}'.",
                code="INDEX_NOT_FOUND",
            )
        if isinstance(body, dict):
            return dict(body)
        return {"raw": body}

    async def search(self, index: str, body: dict) -> dict:
        """Execute a ``_search`` request and return the raw response body."""
        try:
            resp = await self._require_client().search(
                index=index,
                body=body,
                allow_partial_search_results=True,
                track_total_hits=True,
            )
        except Exception as exc:
            raise self._translate_error(exc) from exc

        raw = resp.body if hasattr(resp, "body") else resp
        if isinstance(raw, dict):
            return dict(raw)
        return {"raw": raw}

    def _require_client(self) -> AsyncElasticsearch:
        if self._client is None:
            raise ElkError(
                "ElkClient used outside an async context manager.",
                code="INTERNAL_ERROR",
            )
        return self._client

    @staticmethod
    def _translate_error(exc: BaseException) -> ElkError:
        """Map elasticsearch-py exceptions to user-friendly :class:`ElkError`."""
        if isinstance(exc, AuthenticationException):
            return ElkError(
                "Authentication failed — check the api_key in the profile.",
                code="AUTH_FAILED",
            )
        if isinstance(exc, AuthorizationException):
            return ElkError(
                "API key does not have the required privileges "
                "(needs read + view_index_metadata on the target indices).",
                code="AUTH_FORBIDDEN",
            )
        if isinstance(exc, NotFoundError):
            return ElkError(
                "Index or pattern not found on the cluster.",
                code="INDEX_NOT_FOUND",
            )
        if isinstance(exc, ConnectionTimeout):
            return ElkError(
                "Elasticsearch request timed out.",
                code="TIMEOUT",
                retryable=True,
            )
        if isinstance(exc, EsConnectionError):
            return ElkError(
                f"Cannot reach Elasticsearch cluster: {exc}.",
                code="CONNECTION_ERROR",
                retryable=True,
            )
        if isinstance(exc, ApiError):
            # Generic ES API error (4xx/5xx with body)
            status = getattr(exc, "status_code", 0) or 0
            return ElkError(
                f"Elasticsearch API error ({status}): {exc}",
                code="API_ERROR",
                retryable=500 <= status < 600,
            )
        if isinstance(exc, TransportError):
            return ElkError(
                f"Elasticsearch transport error: {exc}",
                code="TRANSPORT_ERROR",
                retryable=True,
            )
        return ElkError(f"Unexpected ELK client error: {exc}", code="UNKNOWN")
