"""tool config multi department

Revision ID: 4ebf75e0eb74
Revises: e8a97930b1ae
Create Date: 2026-10-06 20:23:51.123692

Introduces the tool-config **scope model**:

* new join table ``gsage_tool_config_departments``;
* new ``gsage_tool_configs.scope`` column (``'org'`` | ``'dept'``);
* at most one global (``scope='org'``) config per ``(org, tool, profile)``
  (partial unique index ``uq_tool_configs_global``);
* department-scoped configs keep their departments disjoint via the join-table
  unique key ``uq_tool_config_dept_scope``;
* legacy ``dept_id`` rows are backfilled into the join table.

The section marked "Manual section" is not autogenerated.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ebf75e0eb74'
down_revision: Union[str, None] = 'e8a97930b1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gsage_tool_config_departments',
    sa.Column('tool_config_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('profile_id', sa.String(length=100), server_default='default', nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['gsage_departments.id'], name=op.f('fk_gsage_tool_config_departments_dept_id_gsage_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_tool_config_departments_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_config_id'], ['gsage_tool_configs.id'], name=op.f('fk_gsage_tool_config_departments_tool_config_id_gsage_tool_configs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_tool_config_departments')),
    sa.UniqueConstraint('org_id', 'tool_name', 'profile_id', 'dept_id', name='uq_tool_config_dept_scope')
    )
    op.create_index(op.f('ix_gsage_tool_config_departments_created_at'), 'gsage_tool_config_departments', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_tool_config_departments_dept_id'), 'gsage_tool_config_departments', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gsage_tool_config_departments_org_id'), 'gsage_tool_config_departments', ['org_id'], unique=False)
    op.create_index(op.f('ix_gsage_tool_config_departments_tool_config_id'), 'gsage_tool_config_departments', ['tool_config_id'], unique=False)
    # ── Manual section: scope column, data preservation and new invariants ──
    # 1) New scope column; pre-existing rows default to global ('org').
    op.add_column(
        'gsage_tool_configs',
        sa.Column(
            'scope',
            sa.String(length=10),
            server_default='org',
            nullable=False,
            comment="'org' = org-wide (all departments); 'dept' = the departments in "
                    "gsage_tool_config_departments. At most one 'org' row per "
                    "(org_id, tool_name, profile_id).",
        ),
    )
    # 2) Anything with a department becomes department-scoped.
    op.execute("UPDATE gsage_tool_configs SET scope = 'dept' WHERE dept_id IS NOT NULL")
    # 3) The old unique constraint used ``dept_id`` with NULLS DISTINCT, so a
    #    database *could* hold several org-wide rows (dept_id IS NULL) for the
    #    same (org, tool, profile). Keep the most recently updated one and drop
    #    the rest so the partial unique index below can be created. In practice
    #    duplicates are anomalies: the old admin API already rejected a second
    #    org-wide row for the same tool/profile.
    op.execute(
        """
        DO $$
        DECLARE removed integer;
        BEGIN
            WITH del AS (
                DELETE FROM gsage_tool_configs dup
                USING gsage_tool_configs keep
                WHERE dup.scope = 'org'
                  AND keep.scope = 'org'
                  AND dup.org_id = keep.org_id
                  AND dup.tool_name = keep.tool_name
                  AND dup.profile_id = keep.profile_id
                  AND dup.id <> keep.id
                  AND (dup.updated_at, dup.id) < (keep.updated_at, keep.id)
                RETURNING 1
            )
            SELECT count(*) INTO removed FROM del;
            IF removed > 0 THEN
                RAISE NOTICE 'tool config migration: removed duplicate org-wide rows';
            END IF;
        END $$;
        """
    )
    # 4) Backfill: one join row per config that had ``dept_id`` set. Must run
    #    BEFORE the ``dept_id`` column is dropped below.
    op.execute(
        """
        INSERT INTO gsage_tool_config_departments
            (id, tool_config_id, org_id, tool_name, profile_id, dept_id,
             created_at, updated_at)
        SELECT gen_random_uuid(), tc.id, tc.org_id, tc.tool_name,
               tc.profile_id, tc.dept_id, now(), now()
        FROM gsage_tool_configs tc
        WHERE tc.dept_id IS NOT NULL
        """
    )
    # 5) Drop the old single-department model.
    op.drop_index(op.f('ix_gsage_tool_configs_dept_id'), table_name='gsage_tool_configs')
    op.drop_constraint(op.f('uq_tool_configs_org_dept_tool_profile'), 'gsage_tool_configs', type_='unique')
    op.drop_constraint(op.f('fk_gsage_tool_configs_dept_id_gsage_departments'), 'gsage_tool_configs', type_='foreignkey')
    op.drop_column('gsage_tool_configs', 'dept_id')
    # 6) New invariants.
    op.create_check_constraint('ck_tool_configs_scope', 'gsage_tool_configs', "scope IN ('org', 'dept')")
    op.create_index(
        'uq_tool_configs_global',
        'gsage_tool_configs',
        ['org_id', 'tool_name', 'profile_id'],
        unique=True,
        postgresql_where=sa.text("scope = 'org'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tool_configs_global', table_name='gsage_tool_configs')
    op.drop_constraint('ck_tool_configs_scope', 'gsage_tool_configs', type_='check')
    op.add_column('gsage_tool_configs', sa.Column('dept_id', sa.UUID(), autoincrement=False, nullable=True, comment='NULL = org-wide config; set = department-specific override.'))
    op.create_foreign_key(op.f('fk_gsage_tool_configs_dept_id_gsage_departments'), 'gsage_tool_configs', 'gsage_departments', ['dept_id'], ['id'], ondelete='SET NULL')
    # Best-effort (lossy) restore of the scalar dept_id: a department-scoped
    # config with several departments keeps only one of them.
    op.execute(
        """
        UPDATE gsage_tool_configs tc
        SET dept_id = tcd.dept_id
        FROM gsage_tool_config_departments tcd
        WHERE tcd.tool_config_id = tc.id AND tc.scope = 'dept'
        """
    )
    op.drop_column('gsage_tool_configs', 'scope')
    op.create_unique_constraint(op.f('uq_tool_configs_org_dept_tool_profile'), 'gsage_tool_configs', ['org_id', 'dept_id', 'tool_name', 'profile_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_gsage_tool_configs_dept_id'), 'gsage_tool_configs', ['dept_id'], unique=False)
    op.drop_index(op.f('ix_gsage_tool_config_departments_tool_config_id'), table_name='gsage_tool_config_departments')
    op.drop_index(op.f('ix_gsage_tool_config_departments_org_id'), table_name='gsage_tool_config_departments')
    op.drop_index(op.f('ix_gsage_tool_config_departments_dept_id'), table_name='gsage_tool_config_departments')
    op.drop_index(op.f('ix_gsage_tool_config_departments_created_at'), table_name='gsage_tool_config_departments')
    op.drop_table('gsage_tool_config_departments')
    # ### end Alembic commands ###
