"""add gsage_org_email_domains

Revision ID: 39fb895cd21b
Revises: 03bdd7da5283
Create Date: 2026-05-04 17:28:32.319113

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39fb895cd21b'
down_revision: Union[str, None] = '03bdd7da5283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gsage_org_email_domains',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False, comment='Lowercased DNS domain name (RFC 1035 max length 253)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_org_email_domains_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_org_email_domains'))
    )
    op.create_index(op.f('ix_gsage_org_email_domains_created_at'), 'gsage_org_email_domains', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_org_email_domains_domain'), 'gsage_org_email_domains', ['domain'], unique=True)
    op.create_index(op.f('ix_gsage_org_email_domains_org_id'), 'gsage_org_email_domains', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gsage_org_email_domains_org_id'), table_name='gsage_org_email_domains')
    op.drop_index(op.f('ix_gsage_org_email_domains_domain'), table_name='gsage_org_email_domains')
    op.drop_index(op.f('ix_gsage_org_email_domains_created_at'), table_name='gsage_org_email_domains')
    op.drop_table('gsage_org_email_domains')
    # ### end Alembic commands ###
