"""add user credentials keychain

Revision ID: 44b5e8cfb02b
Revises: 23922ffa43f1
Create Date: 2026-06-10 18:56:57.980855

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44b5e8cfb02b'
down_revision: Union[str, None] = '23922ffa43f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gsage_user_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False, comment='Denormalised for multi-tenant filtering — credential is scoped to (user, org).'),
    sa.Column('label', sa.String(length=100), nullable=False, comment="Friendly name chosen by the user (e.g. 'AD Corp')."),
    sa.Column('kind', sa.String(length=20), nullable=False, comment='Credential kind: basic | token | api_key | oauth2 | custom.'),
    sa.Column('username_encrypted', sa.LargeBinary(), nullable=True, comment='AES-256-GCM encrypted username.'),
    sa.Column('password_encrypted', sa.LargeBinary(), nullable=True, comment='AES-256-GCM encrypted password.'),
    sa.Column('domain_encrypted', sa.LargeBinary(), nullable=True, comment='AES-256-GCM encrypted domain / tenant.'),
    sa.Column('token_encrypted', sa.LargeBinary(), nullable=True, comment='AES-256-GCM encrypted access / API token.'),
    sa.Column('refresh_token_encrypted', sa.LargeBinary(), nullable=True, comment='AES-256-GCM encrypted OAuth2 refresh token.'),
    sa.Column('extra_fields_encrypted', sa.LargeBinary(), nullable=True, comment='AES-256-GCM encrypted JSON blob of additional fields.'),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True, comment='OAuth2 / token expiration (informational — no auto-refresh).'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('basic', 'token', 'api_key', 'oauth2', 'custom')", name=op.f('ck_gsage_user_credentials_ck_gsage_user_credentials_kind')),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_user_credentials_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_user_credentials_user_id_gsage_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_user_credentials')),
    sa.UniqueConstraint('user_id', 'label', name='uq_gsage_user_credentials_user_label')
    )
    op.create_index(op.f('ix_gsage_user_credentials_created_at'), 'gsage_user_credentials', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_user_credentials_org_id'), 'gsage_user_credentials', ['org_id'], unique=False)
    op.create_index(op.f('ix_gsage_user_credentials_user_id'), 'gsage_user_credentials', ['user_id'], unique=False)
    op.create_table('gsage_user_credential_tool_links',
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Redundant with credential.user_id — denormalised for fast lookups.'),
    sa.Column('tool_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['gsage_user_credentials.id'], name=op.f('fk_gsage_user_credential_tool_links_credential_id_gsage_user_credentials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_user_credential_tool_links_user_id_gsage_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_user_credential_tool_links')),
    sa.UniqueConstraint('credential_id', 'tool_name', name='uq_gsage_user_credential_tool_links_cred_tool')
    )
    op.create_index(op.f('ix_gsage_user_credential_tool_links_credential_id'), 'gsage_user_credential_tool_links', ['credential_id'], unique=False)
    op.create_index(op.f('ix_gsage_user_credential_tool_links_tool_name'), 'gsage_user_credential_tool_links', ['tool_name'], unique=False)
    op.create_index(op.f('ix_gsage_user_credential_tool_links_user_id'), 'gsage_user_credential_tool_links', ['user_id'], unique=False)
    op.create_index('uq_gsage_user_credential_active_per_tool', 'gsage_user_credential_tool_links', ['user_id', 'tool_name'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_gsage_user_credential_active_per_tool', table_name='gsage_user_credential_tool_links', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_gsage_user_credential_tool_links_user_id'), table_name='gsage_user_credential_tool_links')
    op.drop_index(op.f('ix_gsage_user_credential_tool_links_tool_name'), table_name='gsage_user_credential_tool_links')
    op.drop_index(op.f('ix_gsage_user_credential_tool_links_credential_id'), table_name='gsage_user_credential_tool_links')
    op.drop_table('gsage_user_credential_tool_links')
    op.drop_index(op.f('ix_gsage_user_credentials_user_id'), table_name='gsage_user_credentials')
    op.drop_index(op.f('ix_gsage_user_credentials_org_id'), table_name='gsage_user_credentials')
    op.drop_index(op.f('ix_gsage_user_credentials_created_at'), table_name='gsage_user_credentials')
    op.drop_table('gsage_user_credentials')
    # ### end Alembic commands ###
