"""expand_tool_summary_to_500

Revision ID: 23922ffa43f1
Revises: c2d3e4f5a6b7
Create Date: 2026-05-06 19:50:49.000524

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23922ffa43f1'
down_revision: Union[str, None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gsage_tools', 'summary',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               comment='One-line tool summary used in tool search results and LLM context',
               existing_comment='One-line summary (<120 chars) used in tool search results',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gsage_tools', 'summary',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               comment='One-line summary (<120 chars) used in tool search results',
               existing_comment='One-line tool summary used in tool search results and LLM context',
               existing_nullable=True)
    # ### end Alembic commands ###
