"""add prompt library models

Revision ID: 6a649cd87f13
Revises: c7010489007b
Create Date: 2026-06-19 15:49:07.250265

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a649cd87f13'
down_revision: Union[str, None] = 'c7010489007b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gsage_prompt_categories',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['gsage_departments.id'], name=op.f('fk_gsage_prompt_categories_dept_id_gsage_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_prompt_categories_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['gsage_prompt_categories.id'], name=op.f('fk_gsage_prompt_categories_parent_id_gsage_prompt_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_prompt_categories'))
    )
    op.create_index('ix_gsage_prompt_cat_org_dept', 'gsage_prompt_categories', ['org_id', 'dept_id'], unique=False)
    op.create_index(op.f('ix_gsage_prompt_categories_created_at'), 'gsage_prompt_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_prompt_categories_dept_id'), 'gsage_prompt_categories', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gsage_prompt_categories_org_id'), 'gsage_prompt_categories', ['org_id'], unique=False)
    op.create_table('gsage_prompts',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=False, comment='personal | department | organization'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['gsage_prompt_categories.id'], name=op.f('fk_gsage_prompts_category_id_gsage_prompt_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['gsage_users.id'], name=op.f('fk_gsage_prompts_created_by_gsage_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dept_id'], ['gsage_departments.id'], name=op.f('fk_gsage_prompts_dept_id_gsage_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_prompts_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_prompts'))
    )
    op.create_index(op.f('ix_gsage_prompts_created_at'), 'gsage_prompts', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_prompts_dept_id'), 'gsage_prompts', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gsage_prompts_org_id'), 'gsage_prompts', ['org_id'], unique=False)
    op.create_index('ix_gsage_prompts_org_scope', 'gsage_prompts', ['org_id', 'scope'], unique=False)
    op.create_table('gsage_user_prompt_favorites',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['gsage_prompts.id'], name=op.f('fk_gsage_user_prompt_favorites_prompt_id_gsage_prompts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_user_prompt_favorites_user_id_gsage_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'prompt_id', name=op.f('pk_gsage_user_prompt_favorites'))
    )
    op.create_index(op.f('ix_gsage_user_prompt_favorites_created_at'), 'gsage_user_prompt_favorites', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gsage_user_prompt_favorites_created_at'), table_name='gsage_user_prompt_favorites')
    op.drop_table('gsage_user_prompt_favorites')
    op.drop_index('ix_gsage_prompts_org_scope', table_name='gsage_prompts')
    op.drop_index(op.f('ix_gsage_prompts_org_id'), table_name='gsage_prompts')
    op.drop_index(op.f('ix_gsage_prompts_dept_id'), table_name='gsage_prompts')
    op.drop_index(op.f('ix_gsage_prompts_created_at'), table_name='gsage_prompts')
    op.drop_table('gsage_prompts')
    op.drop_index(op.f('ix_gsage_prompt_categories_org_id'), table_name='gsage_prompt_categories')
    op.drop_index(op.f('ix_gsage_prompt_categories_dept_id'), table_name='gsage_prompt_categories')
    op.drop_index(op.f('ix_gsage_prompt_categories_created_at'), table_name='gsage_prompt_categories')
    op.drop_index('ix_gsage_prompt_cat_org_dept', table_name='gsage_prompt_categories')
    op.drop_table('gsage_prompt_categories')
    # ### end Alembic commands ###
