"""add config_namespace and org_tool_settings

Revision ID: f3db92a36a93
Revises: 6a649cd87f13
Create Date: 2026-06-26 23:20:27.071816

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3db92a36a93'
down_revision: Union[str, None] = '6a649cd87f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gsage_org_tool_settings',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False, comment="Tool name or config_namespace (e.g. 'k8s_observe' or 'kubernetes')"),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='When False, the tool is hidden from agents and cannot be called'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_org_tool_settings_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_org_tool_settings')),
    sa.UniqueConstraint('org_id', 'tool_name', name='uq_org_tool_settings')
    )
    op.create_index(op.f('ix_gsage_org_tool_settings_created_at'), 'gsage_org_tool_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_org_tool_settings_org_id'), 'gsage_org_tool_settings', ['org_id'], unique=False)
    op.add_column('gsage_tools', sa.Column('config_namespace', sa.String(length=100), nullable=True, comment="Shared config namespace (e.g. 'kubernetes', 'azure'). When set, config rows for this tool_name OR the namespace are consulted.  NULL = no namespace."))
    op.create_index(op.f('ix_gsage_tools_config_namespace'), 'gsage_tools', ['config_namespace'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gsage_tools_config_namespace'), table_name='gsage_tools')
    op.drop_column('gsage_tools', 'config_namespace')
    op.drop_index(op.f('ix_gsage_org_tool_settings_org_id'), table_name='gsage_org_tool_settings')
    op.drop_index(op.f('ix_gsage_org_tool_settings_created_at'), table_name='gsage_org_tool_settings')
    op.drop_table('gsage_org_tool_settings')
    # ### end Alembic commands ###
