"""initial_schema

Revision ID: 519021a00605
Revises: 
Create Date: 2026-04-26 23:52:40.974538

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '519021a00605'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gsage_organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='Custom agent persona per organization (max 5000 chars)'),
    sa.Column('default_maker_model', sa.String(length=100), nullable=False),
    sa.Column('default_reviewer_model', sa.String(length=100), nullable=False),
    sa.Column('agent_timeout_seconds', sa.Integer(), nullable=False, comment='Global agent execution timeout (max: 300)'),
    sa.Column('max_context_tokens', sa.Integer(), nullable=False, comment='Max context window size for LLM'),
    sa.Column('llm_provider', sa.String(length=20), nullable=False, comment='LLM backend provider: ollama | openai | deepseek | anthropic | gemini'),
    sa.Column('llm_api_key_encrypted', sa.LargeBinary(), nullable=True, comment='AES-256-GCM encrypted API key for the org LLM provider'),
    sa.Column('smtp_config_encrypted', sa.LargeBinary(), nullable=True, comment='AES-256-GCM encrypted SMTP config override (JSON)'),
    sa.Column('auth_providers', sa.String(length=500), nullable=False, comment='Ordered JSON list of auth provider names for login chain'),
    sa.Column('auth_config_encrypted', sa.LargeBinary(), nullable=True, comment='AES-256-GCM encrypted per-provider auth config overrides (JSON)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_organizations'))
    )
    op.create_index(op.f('ix_gsage_organizations_created_at'), 'gsage_organizations', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_organizations_name'), 'gsage_organizations', ['name'], unique=True)
    op.create_index(op.f('ix_gsage_organizations_slug'), 'gsage_organizations', ['slug'], unique=True)
    op.create_table('gsage_permissions',
    sa.Column('tag', sa.String(length=100), nullable=False, comment='Permission tag (e.g., dns:read, tool_config:write)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable description of this permission'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Category: tool, admin, network, threat, etc.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_permissions'))
    )
    op.create_index(op.f('ix_gsage_permissions_created_at'), 'gsage_permissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_permissions_tag'), 'gsage_permissions', ['tag'], unique=True)
    op.create_table('gsage_tool_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False, comment='Cache scope: global, org, or user'),
    sa.Column('org_id', sa.UUID(), nullable=True, comment='Organization ID (NULL for global scope)'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User ID (NULL for global/org scope)'),
    sa.Column('tool_name', sa.String(length=200), nullable=False, comment="Fully-qualified tool name (e.g., 'whois_lookup', 'dns_query')"),
    sa.Column('cache_key', sa.String(length=64), nullable=False, comment='SHA256 hash of tool_name + args + scope identifiers'),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Cached result (JSON-serializable)'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='Cache expiration timestamp (UTC)'),
    sa.Column('hit_count', sa.Integer(), nullable=False, comment='Number of times this cache entry was hit'),
    sa.Column('last_hit_at', sa.DateTime(), nullable=True, comment='Last time this cache entry was accessed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_tool_cache'))
    )
    op.create_index(op.f('ix_gsage_tool_cache_cache_key'), 'gsage_tool_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_gsage_tool_cache_created_at'), 'gsage_tool_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_tool_cache_expires_at'), 'gsage_tool_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_gsage_tool_cache_org_id'), 'gsage_tool_cache', ['org_id'], unique=False)
    op.create_index(op.f('ix_gsage_tool_cache_scope'), 'gsage_tool_cache', ['scope'], unique=False)
    op.create_index(op.f('ix_gsage_tool_cache_tool_name'), 'gsage_tool_cache', ['tool_name'], unique=False)
    op.create_index(op.f('ix_gsage_tool_cache_user_id'), 'gsage_tool_cache', ['user_id'], unique=False)
    op.create_index('ix_tool_cache_expires_at', 'gsage_tool_cache', ['expires_at'], unique=False)
    op.create_index('ix_tool_cache_org_scope', 'gsage_tool_cache', ['org_id', 'scope'], unique=False)
    op.create_index('ix_tool_cache_tool_scope', 'gsage_tool_cache', ['tool_name', 'scope'], unique=False)
    op.create_table('gsage_tools',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Tool name (e.g., dns_lookup)'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='Semantic version (e.g., 1.0.0)'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='Human-readable name'),
    sa.Column('description', sa.Text(), nullable=False, comment='Description for LLM and UI'),
    sa.Column('summary', sa.String(length=200), nullable=True, comment='One-line summary (<120 chars) used in tool search results'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Category: dns, network, decode, threat_intel, etc.'),
    sa.Column('required_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="List of permission tags required (e.g., ['dns:read'])"),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON Schema for input parameters'),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON Schema for output (canonical format)'),
    sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON Schema for per-org configuration (tool_configs table)'),
    sa.Column('config_defaults', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Default config values when no org config exists'),
    sa.Column('state_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON Schema for per-org runtime state (tool_state table)'),
    sa.Column('state_defaults', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Default state values (initial + after reset)'),
    sa.Column('reset_policy', sa.String(length=20), nullable=False, comment='State reset policy: daily, monthly, never'),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False, comment='Individual tool timeout'),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False, comment='Default rate limit per org (can be overridden via tool_state)'),
    sa.Column('requires_config', sa.Boolean(), nullable=False, comment='If true, tool fails without org config'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Admin can disable tool globally'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_tools'))
    )
    op.create_index(op.f('ix_gsage_tools_created_at'), 'gsage_tools', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_tools_name'), 'gsage_tools', ['name'], unique=False)
    op.create_table('gsage_users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Primary email — globally unique across all orgs (used for login)'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='bcrypt hash — NULL for users provisioned by external auth providers'),
    sa.Column('auth_provider', sa.String(length=50), nullable=False, comment='Name of the auth provider that last authenticated this user'),
    sa.Column('external_id', sa.String(length=255), nullable=True, comment='Stable external identifier from the auth provider (e.g. LDAP objectGUID)'),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('secondary_emails', sa.Text(), nullable=True, comment='Alternative email addresses, one per line (newline-separated, max 5)'),
    sa.Column('ai_instructions', sa.Text(), nullable=True, comment='User preferences / custom instructions for the AI assistant (e.g. language, tone, context)'),
    sa.Column('telegram_id', sa.String(length=50), nullable=True, comment='Telegram numeric user ID (as string) for bot sender resolution'),
    sa.Column('otp_secret_encrypted', sa.LargeBinary(), nullable=True, comment='AES-256-GCM encrypted TOTP secret (base32)'),
    sa.Column('otp_enabled', sa.Boolean(), server_default='false', nullable=False, comment='Whether OTP is active for this user (confirmed enrollment)'),
    sa.Column('otp_confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when OTP enrollment was confirmed'),
    sa.Column('otp_backup_codes_encrypted', sa.LargeBinary(), nullable=True, comment='AES-256-GCM encrypted JSON array of bcrypt-hashed backup codes'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_users'))
    )
    op.create_index(op.f('ix_gsage_users_created_at'), 'gsage_users', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_users_email'), 'gsage_users', ['email'], unique=True)
    op.create_index(op.f('ix_gsage_users_external_id'), 'gsage_users', ['external_id'], unique=False)
    op.create_index(op.f('ix_gsage_users_telegram_id'), 'gsage_users', ['telegram_id'], unique=False)
    op.create_table('gsage_approval_rules',
    sa.Column('org_id_pattern', sa.String(length=50), nullable=False, comment="UUID string or '*'"),
    sa.Column('dept_id_pattern', sa.String(length=50), server_default='*', nullable=False, comment="UUID string or '*' (wildcard matches any dept)"),
    sa.Column('user_id_pattern', sa.String(length=50), nullable=False, comment="UUID string or '*'"),
    sa.Column('tool_pattern', sa.String(length=200), nullable=False, comment="Exact tool name or '*'"),
    sa.Column('approver_user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['gsage_users.id'], name=op.f('fk_gsage_approval_rules_approver_user_id_gsage_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_approval_rules')),
    sa.UniqueConstraint('org_id_pattern', 'dept_id_pattern', 'user_id_pattern', 'tool_pattern', name='uq_approval_rule_patterns')
    )
    op.create_index('ix_approval_rule_active', 'gsage_approval_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_gsage_approval_rules_approver_user_id'), 'gsage_approval_rules', ['approver_user_id'], unique=False)
    op.create_index(op.f('ix_gsage_approval_rules_created_at'), 'gsage_approval_rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_approval_rules_is_active'), 'gsage_approval_rules', ['is_active'], unique=False)
    op.create_table('gsage_departments',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='URL- and CLI-friendly identifier (lowercase, hyphens only).'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment="True for the auto-created 'Default' department. Protected from deletion."),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_departments_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_departments')),
    sa.UniqueConstraint('org_id', 'name', name='uq_department_org_name'),
    sa.UniqueConstraint('org_id', 'slug', name='uq_department_org_slug')
    )
    op.create_index(op.f('ix_gsage_departments_created_at'), 'gsage_departments', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_departments_is_active'), 'gsage_departments', ['is_active'], unique=False)
    op.create_index(op.f('ix_gsage_departments_org_id'), 'gsage_departments', ['org_id'], unique=False)
    op.create_table('gsage_groups',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_groups_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_groups')),
    sa.UniqueConstraint('org_id', 'name', name='uq_groups_org_name')
    )
    op.create_index(op.f('ix_gsage_groups_created_at'), 'gsage_groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_groups_org_id'), 'gsage_groups', ['org_id'], unique=False)
    op.create_table('gsage_trusted_devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_hash', sa.String(length=255), nullable=False, comment='SHA-256 hex-digest of the device token'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User-Agent string at the time of trust grant'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP address at the time of trust grant (IPv4 or IPv6)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='UTC datetime after which this trust record is considered expired'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_trusted_devices_user_id_gsage_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_trusted_devices'))
    )
    op.create_index(op.f('ix_gsage_trusted_devices_created_at'), 'gsage_trusted_devices', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_trusted_devices_device_hash'), 'gsage_trusted_devices', ['device_hash'], unique=True)
    op.create_index(op.f('ix_gsage_trusted_devices_user_id'), 'gsage_trusted_devices', ['user_id'], unique=False)
    op.create_table('gsage_user_organizations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='User role within the organization: owner | admin | member | viewer'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin', 'member', 'viewer')", name=op.f('ck_gsage_user_organizations_ck_gsage_user_organizations_role')),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_user_organizations_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_user_organizations_user_id_gsage_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_user_organizations')),
    sa.UniqueConstraint('user_id', 'org_id', name='uq_gsage_user_organizations_user_org')
    )
    op.create_index(op.f('ix_gsage_user_organizations_created_at'), 'gsage_user_organizations', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_user_organizations_org_id'), 'gsage_user_organizations', ['org_id'], unique=False)
    op.create_index(op.f('ix_gsage_user_organizations_user_id'), 'gsage_user_organizations', ['user_id'], unique=False)
    op.create_table('gsage_api_keys',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=True, comment='NULL = org-level key; set = key scoped to a specific department.'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='NULL for org-level keys; set for keys tied to a specific user'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Human-readable name for this API key'),
    sa.Column('key_prefix', sa.String(length=12), nullable=False, comment='First 12 chars of raw key for fast UI display (e.g. gk_live_N7x2)'),
    sa.Column('key_hash', sa.String(length=255), nullable=False, comment='SHA-256 hash of the raw API key (never store the raw key)'),
    sa.Column('environment', sa.String(length=10), nullable=False, comment='Key environment: live | test'),
    sa.Column('scoped_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of permission tags this key has access to'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Expiration date (max 1 year from creation)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Admin can revoke instantly'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interface', sa.String(length=30), nullable=True, comment='Access interface bound to this key (web/api/cli/…). None = auto-resolved.'),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False, comment='Max requests per minute for this key'),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("environment IN ('live', 'test')", name=op.f('ck_gsage_api_keys_ck_gsage_api_keys_environment')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['gsage_users.id'], name=op.f('fk_gsage_api_keys_created_by_user_id_gsage_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dept_id'], ['gsage_departments.id'], name=op.f('fk_gsage_api_keys_dept_id_gsage_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_api_keys_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_api_keys_user_id_gsage_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_api_keys'))
    )
    op.create_index(op.f('ix_gsage_api_keys_created_at'), 'gsage_api_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_api_keys_dept_id'), 'gsage_api_keys', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gsage_api_keys_key_hash'), 'gsage_api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_gsage_api_keys_key_prefix'), 'gsage_api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_gsage_api_keys_org_id'), 'gsage_api_keys', ['org_id'], unique=False)
    op.create_index(op.f('ix_gsage_api_keys_user_id'), 'gsage_api_keys', ['user_id'], unique=False)
    op.create_table('gsage_approval_delegations',
    sa.Column('approval_id', sa.String(length=100), nullable=False, comment='References agno_approvals.id'),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=True, comment='Department context at time of delegation.'),
    sa.Column('requester_user_id', sa.UUID(), nullable=False),
    sa.Column('approver_user_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=200), nullable=False),
    sa.Column('agno_session_id', sa.String(length=500), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True, comment='Human-readable summary injected by the agent via _approval_summary param'),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('continued_at', sa.DateTime(timezone=True), nullable=True, comment='Set when acontinue_run() is first dispatched for this approval.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['gsage_users.id'], name=op.f('fk_gsage_approval_delegations_approver_user_id_gsage_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dept_id'], ['gsage_departments.id'], name=op.f('fk_gsage_approval_delegations_dept_id_gsage_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_approval_delegations_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['gsage_users.id'], name=op.f('fk_gsage_approval_delegations_requester_user_id_gsage_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['gsage_approval_rules.id'], name=op.f('fk_gsage_approval_delegations_rule_id_gsage_approval_rules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_approval_delegations'))
    )
    op.create_index('ix_approval_delegation_approver', 'gsage_approval_delegations', ['approver_user_id'], unique=False)
    op.create_index('ix_approval_delegation_org', 'gsage_approval_delegations', ['org_id'], unique=False)
    op.create_index(op.f('ix_gsage_approval_delegations_approval_id'), 'gsage_approval_delegations', ['approval_id'], unique=True)
    op.create_index(op.f('ix_gsage_approval_delegations_approver_user_id'), 'gsage_approval_delegations', ['approver_user_id'], unique=False)
    op.create_index(op.f('ix_gsage_approval_delegations_created_at'), 'gsage_approval_delegations', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_approval_delegations_dept_id'), 'gsage_approval_delegations', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gsage_approval_delegations_org_id'), 'gsage_approval_delegations', ['org_id'], unique=False)
    op.create_table('gsage_data_stores',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=False, comment='Department that owns this DataStore. Always required.'),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('max_records', sa.Integer(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['gsage_users.id'], name=op.f('fk_gsage_data_stores_created_by_gsage_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dept_id'], ['gsage_departments.id'], name=op.f('fk_gsage_data_stores_dept_id_gsage_departments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_data_stores_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_data_stores')),
    sa.UniqueConstraint('dept_id', 'name', name='uq_datastore_dept_name')
    )
    op.create_index(op.f('ix_gsage_data_stores_created_at'), 'gsage_data_stores', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_data_stores_created_by'), 'gsage_data_stores', ['created_by'], unique=False)
    op.create_index(op.f('ix_gsage_data_stores_dept_id'), 'gsage_data_stores', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gsage_data_stores_is_active'), 'gsage_data_stores', ['is_active'], unique=False)
    op.create_index(op.f('ix_gsage_data_stores_org_id'), 'gsage_data_stores', ['org_id'], unique=False)
    op.create_table('gsage_email_accounts',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=True, comment='Department this account is scoped to. NULL = shared across org.'),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment="Friendly name (e.g., 'SOC Mailbox')"),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Mailbox email address (also default From address)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('imap_host', sa.String(length=255), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('imap_use_tls', sa.Boolean(), nullable=False),
    sa.Column('imap_verify_ssl', sa.Boolean(), nullable=False, comment='Verify TLS certificate on IMAP connection. Set False for self-signed certs.'),
    sa.Column('imap_username', sa.String(length=255), nullable=False),
    sa.Column('imap_password_encrypted', sa.LargeBinary(), nullable=False, comment='AES-256-GCM encrypted IMAP password'),
    sa.Column('imap_folder', sa.String(length=100), nullable=False),
    sa.Column('imap_idle_supported', sa.Boolean(), nullable=False, comment='Whether server supports IMAP IDLE'),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('smtp_verify_ssl', sa.Boolean(), nullable=False, comment='Verify TLS certificate on SMTP connection. Set False for self-signed certs.'),
    sa.Column('smtp_username', sa.String(length=255), server_default='', nullable=False),
    sa.Column('smtp_password_encrypted', sa.LargeBinary(), nullable=True, comment='AES-256-GCM encrypted SMTP password. NULL = unauthenticated relay.'),
    sa.Column('sender_name', sa.String(length=255), nullable=False, comment='Display name in From header'),
    sa.Column('subject_prefix', sa.String(length=50), nullable=True, comment="Prefix for outbound subjects (e.g., '[SOC-AI]')"),
    sa.Column('reply_footer', sa.Text(), nullable=True, comment='Footer appended to outbound emails'),
    sa.Column('unknown_sender_folder', sa.String(length=100), nullable=False, comment='IMAP folder for unrecognized senders'),
    sa.Column('max_email_size_bytes', sa.Integer(), nullable=False),
    sa.Column('polling_interval_seconds', sa.Integer(), nullable=False, comment='Fallback polling interval when IDLE not supported'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['gsage_departments.id'], name=op.f('fk_gsage_email_accounts_dept_id_gsage_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_email_accounts_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_email_accounts'))
    )
    op.create_index(op.f('ix_gsage_email_accounts_created_at'), 'gsage_email_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_email_accounts_dept_id'), 'gsage_email_accounts', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gsage_email_accounts_email'), 'gsage_email_accounts', ['email'], unique=True)
    op.create_index(op.f('ix_gsage_email_accounts_org_id'), 'gsage_email_accounts', ['org_id'], unique=False)
    op.create_table('gsage_group_permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['gsage_departments.id'], name=op.f('fk_gsage_group_permissions_dept_id_gsage_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['gsage_groups.id'], name=op.f('fk_gsage_group_permissions_group_id_gsage_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['gsage_permissions.id'], name=op.f('fk_gsage_group_permissions_permission_id_gsage_permissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_group_permissions'))
    )
    op.create_index(op.f('ix_gsage_group_permissions_dept_id'), 'gsage_group_permissions', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gsage_group_permissions_group_id'), 'gsage_group_permissions', ['group_id'], unique=False)
    op.create_index(op.f('ix_gsage_group_permissions_permission_id'), 'gsage_group_permissions', ['permission_id'], unique=False)
    op.create_index('uq_group_perm_dept', 'gsage_group_permissions', ['group_id', 'permission_id', 'dept_id'], unique=True, postgresql_where=sa.text('dept_id IS NOT NULL'))
    op.create_index('uq_group_perm_global', 'gsage_group_permissions', ['group_id', 'permission_id'], unique=True, postgresql_where=sa.text('dept_id IS NULL'))
    op.create_table('gsage_ingest_jobs',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=True, comment='Department context for this ingest. NULL = org-wide knowledge.'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False, comment="'org' or 'user'"),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='queued | processing | completed | failed'),
    sa.Column('chunks_stored', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.String(length=1000), nullable=True, comment='MinIO object key in the kb-originals bucket. NULL for pre-existing jobs.'),
    sa.Column('source_url', sa.String(length=2000), nullable=True, comment='Origin URL when the job was created from a URL submission. NULL for direct file uploads.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['gsage_departments.id'], name=op.f('fk_gsage_ingest_jobs_dept_id_gsage_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_ingest_jobs_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_ingest_jobs_user_id_gsage_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_ingest_jobs'))
    )
    op.create_index(op.f('ix_gsage_ingest_jobs_created_at'), 'gsage_ingest_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_ingest_jobs_dept_id'), 'gsage_ingest_jobs', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gsage_ingest_jobs_org_id'), 'gsage_ingest_jobs', ['org_id'], unique=False)
    op.create_index(op.f('ix_gsage_ingest_jobs_status'), 'gsage_ingest_jobs', ['status'], unique=False)
    op.create_index('ix_ingest_job_org_status', 'gsage_ingest_jobs', ['org_id', 'status'], unique=False)
    op.create_index('ix_ingest_job_user', 'gsage_ingest_jobs', ['user_id'], unique=False)
    op.create_table('gsage_interface_profiles',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=True, comment='NULL = org-wide profile; set = department-specific override.'),
    sa.Column('interface', sa.String(length=30), nullable=False, comment='Access interface: web, email, telegram, whatsapp, slack, api, cli'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User-scoped profile; NULL means org-wide default'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable description of this interface profile'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='Channel-specific system prompt appended after base/org/user prompts'),
    sa.Column('mode', sa.String(length=10), nullable=False, comment='allowlist = only these tags; denylist = all except these tags'),
    sa.Column('tool_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Tool permission tags for the allowlist/denylist'),
    sa.Column('interface_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Interface credentials / settings (phone, bot_token, webhook_url, …)'),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='UX preferences: max_message_length, default_format, locale, …'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['gsage_departments.id'], name=op.f('fk_gsage_interface_profiles_dept_id_gsage_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_interface_profiles_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_interface_profiles_user_id_gsage_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_interface_profiles'))
    )
    op.create_index(op.f('ix_gsage_interface_profiles_created_at'), 'gsage_interface_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_interface_profiles_dept_id'), 'gsage_interface_profiles', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gsage_interface_profiles_interface'), 'gsage_interface_profiles', ['interface'], unique=False)
    op.create_index(op.f('ix_gsage_interface_profiles_org_id'), 'gsage_interface_profiles', ['org_id'], unique=False)
    op.create_index(op.f('ix_gsage_interface_profiles_user_id'), 'gsage_interface_profiles', ['user_id'], unique=False)
    op.create_index('uq_interface_profile_dept_iface_org', 'gsage_interface_profiles', ['org_id', 'dept_id', 'interface'], unique=True, postgresql_where=sa.text('user_id IS NULL'))
    op.create_index('uq_interface_profile_dept_iface_user', 'gsage_interface_profiles', ['org_id', 'dept_id', 'interface', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('gsage_scheduled_jobs',
    sa.Column('org_id', sa.UUID(), nullable=False, comment='Owning organization (tenant isolation key).'),
    sa.Column('dept_id', sa.UUID(), nullable=True, comment='Department that owns this job. NULL = org-wide job.'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment="Owning user — PROMPT_RUN jobs execute with this user's permissions."),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Human-readable name for the job.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional longer description / notes.'),
    sa.Column('job_type', sa.String(length=20), nullable=False, comment='PROMPT_RUN | SYSTEM_TASK'),
    sa.Column('cron_expression', sa.String(length=100), nullable=False, comment="Standard 5-field crontab expression, e.g. '*/15 * * * *'."),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False, comment="IANA timezone name for cron evaluation, e.g. 'America/Sao_Paulo'."),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True, comment='Job is skipped if now < starts_at. NULL means always.'),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True, comment='Job self-deactivates after ends_at. NULL means indefinite.'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Manual kill-switch. Set False to pause without deleting.'),
    sa.Column('max_runs', sa.Integer(), nullable=True, comment='Auto-deactivate after this many successful executions. NULL = unlimited.'),
    sa.Column('run_count', sa.Integer(), server_default='0', nullable=False, comment='Total successful executions so far.'),
    sa.Column('prompt_content', sa.Text(), nullable=True, comment='[PROMPT_RUN] The prompt text sent to the agent.'),
    sa.Column('prompt_conversation_id', sa.UUID(), nullable=True, comment='[PROMPT_RUN] Target conversation UUID. NULL = create a fresh conversation each run.'),
    sa.Column('prompt_output_format', sa.String(length=20), server_default='markdown', nullable=False, comment="[PROMPT_RUN] Output format: 'markdown' | 'plain'."),
    sa.Column('task_name', sa.String(length=300), nullable=True, comment='[SYSTEM_TASK] Fully-qualified Celery task name.'),
    sa.Column('task_kwargs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='[SYSTEM_TASK] JSON kwargs passed to the Celery task.'),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the most recent execution attempt.'),
    sa.Column('last_run_status', sa.String(length=20), nullable=True, comment='PENDING | RUNNING | SUCCESS | FAILURE | SKIPPED'),
    sa.Column('last_run_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Result payload from the last execution (truncated if large).'),
    sa.Column('redbeat_key', sa.String(length=400), nullable=True, comment='RedBeat Redis key for this entry — set on sync, cleared on remove.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['gsage_departments.id'], name=op.f('fk_gsage_scheduled_jobs_dept_id_gsage_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_scheduled_jobs_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_scheduled_jobs_user_id_gsage_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_scheduled_jobs')),
    sa.UniqueConstraint('redbeat_key', name=op.f('uq_gsage_scheduled_jobs_redbeat_key'))
    )
    op.create_index(op.f('ix_gsage_scheduled_jobs_created_at'), 'gsage_scheduled_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_scheduled_jobs_dept_id'), 'gsage_scheduled_jobs', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gsage_scheduled_jobs_org_id'), 'gsage_scheduled_jobs', ['org_id'], unique=False)
    op.create_index(op.f('ix_gsage_scheduled_jobs_user_id'), 'gsage_scheduled_jobs', ['user_id'], unique=False)
    op.create_table('gsage_tool_configs',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=True, comment='NULL = org-wide config; set = department-specific override.'),
    sa.Column('tool_name', sa.String(length=100), nullable=False, comment='Matches tool registry name (e.g., dns_lookup)'),
    sa.Column('profile_id', sa.String(length=100), server_default='default', nullable=False, comment="Profile identifier (e.g. 'vt_free', 'misp_prod'). 'default' for single-config tools."),
    sa.Column('description', sa.Text(), nullable=True, comment="Human-readable label for this profile (e.g. 'VirusTotal free tier — 4 req/min')"),
    sa.Column('config_encrypted', sa.LargeBinary(), nullable=False, comment='AES-256-GCM encrypted JSONB payload'),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True, comment='Admin who last modified this config'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['gsage_departments.id'], name=op.f('fk_gsage_tool_configs_dept_id_gsage_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_tool_configs_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['gsage_users.id'], name=op.f('fk_gsage_tool_configs_updated_by_user_id_gsage_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_tool_configs')),
    sa.UniqueConstraint('org_id', 'dept_id', 'tool_name', 'profile_id', name='uq_tool_configs_org_dept_tool_profile')
    )
    op.create_index(op.f('ix_gsage_tool_configs_created_at'), 'gsage_tool_configs', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_tool_configs_dept_id'), 'gsage_tool_configs', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gsage_tool_configs_org_id'), 'gsage_tool_configs', ['org_id'], unique=False)
    op.create_table('gsage_tool_state',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=True, comment='NULL = org-wide state; set = department-specific state.'),
    sa.Column('tool_name', sa.String(length=100), nullable=False, comment='Matches tool registry name'),
    sa.Column('profile_id', sa.String(length=100), server_default='default', nullable=False, comment='Config profile this state belongs to. Mirrors GSageToolConfig.profile_id.'),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Tool-managed runtime state (counters, quotas, timestamps)'),
    sa.Column('reset_policy', sa.String(length=20), nullable=False, comment='When to auto-reset: daily, monthly, never'),
    sa.Column('last_reset_at', sa.DateTime(timezone=True), nullable=True, comment='Last time state was reset by scheduled task'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['gsage_departments.id'], name=op.f('fk_gsage_tool_state_dept_id_gsage_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_tool_state_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_tool_state')),
    sa.UniqueConstraint('org_id', 'dept_id', 'tool_name', 'profile_id', name='uq_tool_state_org_dept_tool_profile')
    )
    op.create_index(op.f('ix_gsage_tool_state_created_at'), 'gsage_tool_state', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_tool_state_dept_id'), 'gsage_tool_state', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gsage_tool_state_org_id'), 'gsage_tool_state', ['org_id'], unique=False)
    op.create_index('uix_tool_state_org_tool_profile_no_dept', 'gsage_tool_state', ['org_id', 'tool_name', 'profile_id'], unique=True, postgresql_where='dept_id IS NULL')
    op.create_table('gsage_user_departments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='admin | member | viewer'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'member', 'viewer')", name=op.f('ck_gsage_user_departments_ck_user_department_role')),
    sa.ForeignKeyConstraint(['dept_id'], ['gsage_departments.id'], name=op.f('fk_gsage_user_departments_dept_id_gsage_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_user_departments_user_id_gsage_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_user_departments')),
    sa.UniqueConstraint('user_id', 'dept_id', name='uq_user_department')
    )
    op.create_index(op.f('ix_gsage_user_departments_created_at'), 'gsage_user_departments', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_user_departments_dept_id'), 'gsage_user_departments', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gsage_user_departments_user_id'), 'gsage_user_departments', ['user_id'], unique=False)
    op.create_table('gsage_user_groups',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['gsage_groups.id'], name=op.f('fk_gsage_user_groups_group_id_gsage_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_user_groups_user_id_gsage_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id', name=op.f('pk_gsage_user_groups'))
    )
    op.create_table('gsage_data_store_records',
    sa.Column('datastore_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['datastore_id'], ['gsage_data_stores.id'], name=op.f('fk_gsage_data_store_records_datastore_id_gsage_data_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_data_store_records'))
    )
    op.create_index('ix_datastore_record_data_gin', 'gsage_data_store_records', ['data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_gsage_data_store_records_created_at'), 'gsage_data_store_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_data_store_records_datastore_id'), 'gsage_data_store_records', ['datastore_id'], unique=False)
    op.create_table('gsage_tenant_sessions',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=True, comment='Active department at session creation. NULL = session not dept-scoped.'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Set when session is initiated via JWT (human user)'),
    sa.Column('api_key_id', sa.UUID(), nullable=True, comment='Set when session is initiated via API key (service account)'),
    sa.Column('agno_session_id', sa.String(length=255), nullable=False, comment='Agno session ID (foreign key into agno_sessions table)'),
    sa.Column('title', sa.String(length=500), nullable=True, comment='Human-readable session title (auto-generated from first message or user-defined)'),
    sa.Column('source', sa.String(length=20), server_default='web', nullable=False, comment='Channel that initiated this session: web | cli | api | email | scheduled'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['gsage_api_keys.id'], name=op.f('fk_gsage_tenant_sessions_api_key_id_gsage_api_keys'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dept_id'], ['gsage_departments.id'], name=op.f('fk_gsage_tenant_sessions_dept_id_gsage_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_tenant_sessions_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_tenant_sessions_user_id_gsage_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_tenant_sessions'))
    )
    op.create_index(op.f('ix_gsage_tenant_sessions_agno_session_id'), 'gsage_tenant_sessions', ['agno_session_id'], unique=True)
    op.create_index(op.f('ix_gsage_tenant_sessions_api_key_id'), 'gsage_tenant_sessions', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_gsage_tenant_sessions_created_at'), 'gsage_tenant_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_tenant_sessions_dept_id'), 'gsage_tenant_sessions', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gsage_tenant_sessions_org_id'), 'gsage_tenant_sessions', ['org_id'], unique=False)
    op.create_index(op.f('ix_gsage_tenant_sessions_user_id'), 'gsage_tenant_sessions', ['user_id'], unique=False)
    op.create_table('gsage_agent_runs',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('agno_run_id', sa.String(length=255), nullable=True, comment='Agno run ID from agno_sessions.runs[]'),
    sa.Column('agent_type', sa.String(length=20), nullable=False, comment='Type of agent that executed this run: maker | reviewer'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Run lifecycle status: pending | running | completed | failed | timeout'),
    sa.Column('input_tokens', sa.Integer(), nullable=True, comment='Number of input tokens consumed'),
    sa.Column('output_tokens', sa.Integer(), nullable=True, comment='Number of output tokens generated'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='Execution duration in milliseconds'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error details if status is failed or timeout'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("agent_type IN ('maker', 'reviewer')", name=op.f('ck_gsage_agent_runs_ck_gsage_agent_runs_agent_type')),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'timeout')", name=op.f('ck_gsage_agent_runs_ck_gsage_agent_runs_status')),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_agent_runs_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['gsage_tenant_sessions.id'], name=op.f('fk_gsage_agent_runs_session_id_gsage_tenant_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_agent_runs'))
    )
    op.create_index(op.f('ix_gsage_agent_runs_agno_run_id'), 'gsage_agent_runs', ['agno_run_id'], unique=False)
    op.create_index(op.f('ix_gsage_agent_runs_created_at'), 'gsage_agent_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_agent_runs_org_id'), 'gsage_agent_runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_gsage_agent_runs_session_id'), 'gsage_agent_runs', ['session_id'], unique=False)
    op.create_table('gsage_background_tasks',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=True, comment='Department context when this task was dispatched.'),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('gsage_session_id', sa.UUID(), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('profile_id', sa.String(length=255), nullable=False),
    sa.Column('tool_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_context_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audit_context_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['gsage_departments.id'], name=op.f('fk_gsage_background_tasks_dept_id_gsage_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gsage_session_id'], ['gsage_tenant_sessions.id'], name=op.f('fk_gsage_background_tasks_gsage_session_id_gsage_tenant_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_background_tasks_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_background_tasks_user_id_gsage_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_background_tasks'))
    )
    op.create_index('ix_bg_tasks_org_created', 'gsage_background_tasks', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_bg_tasks_session_notify', 'gsage_background_tasks', ['gsage_session_id', 'notified', 'status'], unique=False)
    op.create_index(op.f('ix_gsage_background_tasks_created_at'), 'gsage_background_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_background_tasks_dept_id'), 'gsage_background_tasks', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gsage_background_tasks_gsage_session_id'), 'gsage_background_tasks', ['gsage_session_id'], unique=False)
    op.create_index(op.f('ix_gsage_background_tasks_notified'), 'gsage_background_tasks', ['notified'], unique=False)
    op.create_index(op.f('ix_gsage_background_tasks_org_id'), 'gsage_background_tasks', ['org_id'], unique=False)
    op.create_index(op.f('ix_gsage_background_tasks_status'), 'gsage_background_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_gsage_background_tasks_tool_name'), 'gsage_background_tasks', ['tool_name'], unique=False)
    op.create_index(op.f('ix_gsage_background_tasks_user_id'), 'gsage_background_tasks', ['user_id'], unique=False)
    op.create_table('gsage_channel_conversations',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False, comment='Channel name: telegram | discord | slack | whatsapp'),
    sa.Column('channel_chat_id', sa.String(length=100), nullable=False, comment='Channel-native chat/conversation identifier'),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=False, comment='Total messages exchanged in this conversation'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_channel_conversations_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['gsage_tenant_sessions.id'], name=op.f('fk_gsage_channel_conversations_session_id_gsage_tenant_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_channel_conversations_user_id_gsage_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_channel_conversations')),
    sa.UniqueConstraint('org_id', 'channel', 'channel_chat_id', 'user_id', name='uq_channel_conversation_org_channel_chat_user')
    )
    op.create_index(op.f('ix_gsage_channel_conversations_created_at'), 'gsage_channel_conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_channel_conversations_org_id'), 'gsage_channel_conversations', ['org_id'], unique=False)
    op.create_index(op.f('ix_gsage_channel_conversations_session_id'), 'gsage_channel_conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_gsage_channel_conversations_user_id'), 'gsage_channel_conversations', ['user_id'], unique=False)
    op.create_table('gsage_channel_messages',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Resolved GSageUser (inbound) or None if unknown sender'),
    sa.Column('channel', sa.String(length=50), nullable=False, comment='Channel name: telegram | discord | slack | whatsapp'),
    sa.Column('channel_chat_id', sa.String(length=100), nullable=False, comment='Channel-native chat/conversation identifier (e.g. Telegram chat_id)'),
    sa.Column('channel_message_id', sa.String(length=100), nullable=False, comment='Channel-native message identifier for idempotency'),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='gsagechanneldirection', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='gsagechannelstatus', native_enum=False), nullable=False),
    sa.Column('text', sa.Text(), nullable=True, comment='Plain text content of the message'),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error detail when status=failed'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_channel_messages_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['gsage_tenant_sessions.id'], name=op.f('fk_gsage_channel_messages_session_id_gsage_tenant_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_channel_messages_user_id_gsage_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_channel_messages'))
    )
    op.create_index(op.f('ix_gsage_channel_messages_channel'), 'gsage_channel_messages', ['channel'], unique=False)
    op.create_index(op.f('ix_gsage_channel_messages_channel_chat_id'), 'gsage_channel_messages', ['channel_chat_id'], unique=False)
    op.create_index('ix_gsage_channel_messages_channel_msg_id', 'gsage_channel_messages', ['channel', 'channel_message_id'], unique=True)
    op.create_index(op.f('ix_gsage_channel_messages_created_at'), 'gsage_channel_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_channel_messages_org_id'), 'gsage_channel_messages', ['org_id'], unique=False)
    op.create_index(op.f('ix_gsage_channel_messages_session_id'), 'gsage_channel_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_gsage_channel_messages_user_id'), 'gsage_channel_messages', ['user_id'], unique=False)
    op.create_table('gsage_email_threads',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('thread_subject', sa.String(length=500), nullable=False, comment='Normalized subject (without Re:/Fwd:)'),
    sa.Column('session_id', sa.UUID(), nullable=True, comment='Links thread to an ongoing tenant session'),
    sa.Column('first_message_id', sa.UUID(), nullable=True),
    sa.Column('last_message_id', sa.UUID(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['first_message_id'], ['gsage_email_messages.id'], name='fk_thread_first_message', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['last_message_id'], ['gsage_email_messages.id'], name='fk_thread_last_message', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_email_threads_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['gsage_tenant_sessions.id'], name=op.f('fk_gsage_email_threads_session_id_gsage_tenant_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_email_threads_user_id_gsage_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_email_threads'))
    )
    op.create_index(op.f('ix_gsage_email_threads_created_at'), 'gsage_email_threads', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_email_threads_org_id'), 'gsage_email_threads', ['org_id'], unique=False)
    op.create_index(op.f('ix_gsage_email_threads_session_id'), 'gsage_email_threads', ['session_id'], unique=False)
    op.create_index(op.f('ix_gsage_email_threads_user_id'), 'gsage_email_threads', ['user_id'], unique=False)
    op.create_table('gsage_files',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=True, comment='Department context when this file was generated.'),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=True, comment='Agno run/trace ID that produced this file'),
    sa.Column('filename', sa.String(length=512), nullable=False, comment='Original filename shown to the user'),
    sa.Column('content_type', sa.String(length=200), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False, comment='Full object key in MinIO bucket'),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable description produced by the tool'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='UTC datetime when this file should be purged. NULL = never.'),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True, comment='Set when the Celery purge task deleted the MinIO object.'),
    sa.Column('category', sa.String(length=20), server_default='generated', nullable=False, comment="'generated' = tool output, 'template' = user-uploaded document, 'attachment' = chat message attachment"),
    sa.Column('scope', sa.String(length=20), server_default='user', nullable=False, comment="'user' = private to uploader, 'department' = visible to all department members, 'organization' = visible to all org members"),
    sa.Column('session_id', sa.UUID(), nullable=True, comment='Chat session this attachment belongs to. NULL for generated/template files.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['gsage_departments.id'], name=op.f('fk_gsage_files_dept_id_gsage_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_files_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['gsage_tenant_sessions.id'], name=op.f('fk_gsage_files_session_id_gsage_tenant_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_files_user_id_gsage_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_files'))
    )
    op.create_index(op.f('ix_gsage_files_category'), 'gsage_files', ['category'], unique=False)
    op.create_index(op.f('ix_gsage_files_created_at'), 'gsage_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_files_dept_id'), 'gsage_files', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gsage_files_expires_at'), 'gsage_files', ['expires_at'], unique=False)
    op.create_index('ix_gsage_files_org_category', 'gsage_files', ['org_id', 'category'], unique=False)
    op.create_index('ix_gsage_files_org_expires', 'gsage_files', ['org_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_gsage_files_org_id'), 'gsage_files', ['org_id'], unique=False)
    op.create_index(op.f('ix_gsage_files_purged_at'), 'gsage_files', ['purged_at'], unique=False)
    op.create_index(op.f('ix_gsage_files_scope'), 'gsage_files', ['scope'], unique=False)
    op.create_index('ix_gsage_files_session', 'gsage_files', ['session_id'], unique=False)
    op.create_index(op.f('ix_gsage_files_tool_name'), 'gsage_files', ['tool_name'], unique=False)
    op.create_index(op.f('ix_gsage_files_trace_id'), 'gsage_files', ['trace_id'], unique=False)
    op.create_index(op.f('ix_gsage_files_user_id'), 'gsage_files', ['user_id'], unique=False)
    op.create_table('gsage_email_messages',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User who sent (inbound) or recipient (outbound)'),
    sa.Column('email_account_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=500), nullable=False, comment='IMAP Message-ID header (globally unique)'),
    sa.Column('in_reply_to', sa.String(length=500), nullable=True, comment='In-Reply-To header for threading'),
    sa.Column('references', sa.Text(), nullable=True, comment='References header (space-separated Message-IDs)'),
    sa.Column('thread_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='gsageemaildirection', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='gsageemailstatus', native_enum=False), nullable=False),
    sa.Column('from_addr', sa.String(length=255), nullable=False),
    sa.Column('to_addr', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True, comment='Plain text body'),
    sa.Column('body_html', sa.Text(), nullable=True, comment='HTML body'),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if status=failed'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_account_id'], ['gsage_email_accounts.id'], name=op.f('fk_gsage_email_messages_email_account_id_gsage_email_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_email_messages_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['gsage_tenant_sessions.id'], name=op.f('fk_gsage_email_messages_session_id_gsage_tenant_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['gsage_email_threads.id'], name=op.f('fk_gsage_email_messages_thread_id_gsage_email_threads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_email_messages_user_id_gsage_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_email_messages'))
    )
    op.create_index(op.f('ix_gsage_email_messages_created_at'), 'gsage_email_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_email_messages_email_account_id'), 'gsage_email_messages', ['email_account_id'], unique=False)
    op.create_index(op.f('ix_gsage_email_messages_message_id'), 'gsage_email_messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_gsage_email_messages_org_id'), 'gsage_email_messages', ['org_id'], unique=False)
    op.create_index(op.f('ix_gsage_email_messages_session_id'), 'gsage_email_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_gsage_email_messages_thread_id'), 'gsage_email_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_gsage_email_messages_user_id'), 'gsage_email_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gsage_email_messages_user_id'), table_name='gsage_email_messages')
    op.drop_index(op.f('ix_gsage_email_messages_thread_id'), table_name='gsage_email_messages')
    op.drop_index(op.f('ix_gsage_email_messages_session_id'), table_name='gsage_email_messages')
    op.drop_index(op.f('ix_gsage_email_messages_org_id'), table_name='gsage_email_messages')
    op.drop_index(op.f('ix_gsage_email_messages_message_id'), table_name='gsage_email_messages')
    op.drop_index(op.f('ix_gsage_email_messages_email_account_id'), table_name='gsage_email_messages')
    op.drop_index(op.f('ix_gsage_email_messages_created_at'), table_name='gsage_email_messages')
    op.drop_table('gsage_email_messages')
    op.drop_index(op.f('ix_gsage_files_user_id'), table_name='gsage_files')
    op.drop_index(op.f('ix_gsage_files_trace_id'), table_name='gsage_files')
    op.drop_index(op.f('ix_gsage_files_tool_name'), table_name='gsage_files')
    op.drop_index('ix_gsage_files_session', table_name='gsage_files')
    op.drop_index(op.f('ix_gsage_files_scope'), table_name='gsage_files')
    op.drop_index(op.f('ix_gsage_files_purged_at'), table_name='gsage_files')
    op.drop_index(op.f('ix_gsage_files_org_id'), table_name='gsage_files')
    op.drop_index('ix_gsage_files_org_expires', table_name='gsage_files')
    op.drop_index('ix_gsage_files_org_category', table_name='gsage_files')
    op.drop_index(op.f('ix_gsage_files_expires_at'), table_name='gsage_files')
    op.drop_index(op.f('ix_gsage_files_dept_id'), table_name='gsage_files')
    op.drop_index(op.f('ix_gsage_files_created_at'), table_name='gsage_files')
    op.drop_index(op.f('ix_gsage_files_category'), table_name='gsage_files')
    op.drop_table('gsage_files')
    op.drop_index(op.f('ix_gsage_email_threads_user_id'), table_name='gsage_email_threads')
    op.drop_index(op.f('ix_gsage_email_threads_session_id'), table_name='gsage_email_threads')
    op.drop_index(op.f('ix_gsage_email_threads_org_id'), table_name='gsage_email_threads')
    op.drop_index(op.f('ix_gsage_email_threads_created_at'), table_name='gsage_email_threads')
    op.drop_table('gsage_email_threads')
    op.drop_index(op.f('ix_gsage_channel_messages_user_id'), table_name='gsage_channel_messages')
    op.drop_index(op.f('ix_gsage_channel_messages_session_id'), table_name='gsage_channel_messages')
    op.drop_index(op.f('ix_gsage_channel_messages_org_id'), table_name='gsage_channel_messages')
    op.drop_index(op.f('ix_gsage_channel_messages_created_at'), table_name='gsage_channel_messages')
    op.drop_index('ix_gsage_channel_messages_channel_msg_id', table_name='gsage_channel_messages')
    op.drop_index(op.f('ix_gsage_channel_messages_channel_chat_id'), table_name='gsage_channel_messages')
    op.drop_index(op.f('ix_gsage_channel_messages_channel'), table_name='gsage_channel_messages')
    op.drop_table('gsage_channel_messages')
    op.drop_index(op.f('ix_gsage_channel_conversations_user_id'), table_name='gsage_channel_conversations')
    op.drop_index(op.f('ix_gsage_channel_conversations_session_id'), table_name='gsage_channel_conversations')
    op.drop_index(op.f('ix_gsage_channel_conversations_org_id'), table_name='gsage_channel_conversations')
    op.drop_index(op.f('ix_gsage_channel_conversations_created_at'), table_name='gsage_channel_conversations')
    op.drop_table('gsage_channel_conversations')
    op.drop_index(op.f('ix_gsage_background_tasks_user_id'), table_name='gsage_background_tasks')
    op.drop_index(op.f('ix_gsage_background_tasks_tool_name'), table_name='gsage_background_tasks')
    op.drop_index(op.f('ix_gsage_background_tasks_status'), table_name='gsage_background_tasks')
    op.drop_index(op.f('ix_gsage_background_tasks_org_id'), table_name='gsage_background_tasks')
    op.drop_index(op.f('ix_gsage_background_tasks_notified'), table_name='gsage_background_tasks')
    op.drop_index(op.f('ix_gsage_background_tasks_gsage_session_id'), table_name='gsage_background_tasks')
    op.drop_index(op.f('ix_gsage_background_tasks_dept_id'), table_name='gsage_background_tasks')
    op.drop_index(op.f('ix_gsage_background_tasks_created_at'), table_name='gsage_background_tasks')
    op.drop_index('ix_bg_tasks_session_notify', table_name='gsage_background_tasks')
    op.drop_index('ix_bg_tasks_org_created', table_name='gsage_background_tasks')
    op.drop_table('gsage_background_tasks')
    op.drop_index(op.f('ix_gsage_agent_runs_session_id'), table_name='gsage_agent_runs')
    op.drop_index(op.f('ix_gsage_agent_runs_org_id'), table_name='gsage_agent_runs')
    op.drop_index(op.f('ix_gsage_agent_runs_created_at'), table_name='gsage_agent_runs')
    op.drop_index(op.f('ix_gsage_agent_runs_agno_run_id'), table_name='gsage_agent_runs')
    op.drop_table('gsage_agent_runs')
    op.drop_index(op.f('ix_gsage_tenant_sessions_user_id'), table_name='gsage_tenant_sessions')
    op.drop_index(op.f('ix_gsage_tenant_sessions_org_id'), table_name='gsage_tenant_sessions')
    op.drop_index(op.f('ix_gsage_tenant_sessions_dept_id'), table_name='gsage_tenant_sessions')
    op.drop_index(op.f('ix_gsage_tenant_sessions_created_at'), table_name='gsage_tenant_sessions')
    op.drop_index(op.f('ix_gsage_tenant_sessions_api_key_id'), table_name='gsage_tenant_sessions')
    op.drop_index(op.f('ix_gsage_tenant_sessions_agno_session_id'), table_name='gsage_tenant_sessions')
    op.drop_table('gsage_tenant_sessions')
    op.drop_index(op.f('ix_gsage_data_store_records_datastore_id'), table_name='gsage_data_store_records')
    op.drop_index(op.f('ix_gsage_data_store_records_created_at'), table_name='gsage_data_store_records')
    op.drop_index('ix_datastore_record_data_gin', table_name='gsage_data_store_records', postgresql_using='gin')
    op.drop_table('gsage_data_store_records')
    op.drop_table('gsage_user_groups')
    op.drop_index(op.f('ix_gsage_user_departments_user_id'), table_name='gsage_user_departments')
    op.drop_index(op.f('ix_gsage_user_departments_dept_id'), table_name='gsage_user_departments')
    op.drop_index(op.f('ix_gsage_user_departments_created_at'), table_name='gsage_user_departments')
    op.drop_table('gsage_user_departments')
    op.drop_index('uix_tool_state_org_tool_profile_no_dept', table_name='gsage_tool_state', postgresql_where='dept_id IS NULL')
    op.drop_index(op.f('ix_gsage_tool_state_org_id'), table_name='gsage_tool_state')
    op.drop_index(op.f('ix_gsage_tool_state_dept_id'), table_name='gsage_tool_state')
    op.drop_index(op.f('ix_gsage_tool_state_created_at'), table_name='gsage_tool_state')
    op.drop_table('gsage_tool_state')
    op.drop_index(op.f('ix_gsage_tool_configs_org_id'), table_name='gsage_tool_configs')
    op.drop_index(op.f('ix_gsage_tool_configs_dept_id'), table_name='gsage_tool_configs')
    op.drop_index(op.f('ix_gsage_tool_configs_created_at'), table_name='gsage_tool_configs')
    op.drop_table('gsage_tool_configs')
    op.drop_index(op.f('ix_gsage_scheduled_jobs_user_id'), table_name='gsage_scheduled_jobs')
    op.drop_index(op.f('ix_gsage_scheduled_jobs_org_id'), table_name='gsage_scheduled_jobs')
    op.drop_index(op.f('ix_gsage_scheduled_jobs_dept_id'), table_name='gsage_scheduled_jobs')
    op.drop_index(op.f('ix_gsage_scheduled_jobs_created_at'), table_name='gsage_scheduled_jobs')
    op.drop_table('gsage_scheduled_jobs')
    op.drop_index('uq_interface_profile_dept_iface_user', table_name='gsage_interface_profiles', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uq_interface_profile_dept_iface_org', table_name='gsage_interface_profiles', postgresql_where=sa.text('user_id IS NULL'))
    op.drop_index(op.f('ix_gsage_interface_profiles_user_id'), table_name='gsage_interface_profiles')
    op.drop_index(op.f('ix_gsage_interface_profiles_org_id'), table_name='gsage_interface_profiles')
    op.drop_index(op.f('ix_gsage_interface_profiles_interface'), table_name='gsage_interface_profiles')
    op.drop_index(op.f('ix_gsage_interface_profiles_dept_id'), table_name='gsage_interface_profiles')
    op.drop_index(op.f('ix_gsage_interface_profiles_created_at'), table_name='gsage_interface_profiles')
    op.drop_table('gsage_interface_profiles')
    op.drop_index('ix_ingest_job_user', table_name='gsage_ingest_jobs')
    op.drop_index('ix_ingest_job_org_status', table_name='gsage_ingest_jobs')
    op.drop_index(op.f('ix_gsage_ingest_jobs_status'), table_name='gsage_ingest_jobs')
    op.drop_index(op.f('ix_gsage_ingest_jobs_org_id'), table_name='gsage_ingest_jobs')
    op.drop_index(op.f('ix_gsage_ingest_jobs_dept_id'), table_name='gsage_ingest_jobs')
    op.drop_index(op.f('ix_gsage_ingest_jobs_created_at'), table_name='gsage_ingest_jobs')
    op.drop_table('gsage_ingest_jobs')
    op.drop_index('uq_group_perm_global', table_name='gsage_group_permissions', postgresql_where=sa.text('dept_id IS NULL'))
    op.drop_index('uq_group_perm_dept', table_name='gsage_group_permissions', postgresql_where=sa.text('dept_id IS NOT NULL'))
    op.drop_index(op.f('ix_gsage_group_permissions_permission_id'), table_name='gsage_group_permissions')
    op.drop_index(op.f('ix_gsage_group_permissions_group_id'), table_name='gsage_group_permissions')
    op.drop_index(op.f('ix_gsage_group_permissions_dept_id'), table_name='gsage_group_permissions')
    op.drop_table('gsage_group_permissions')
    op.drop_index(op.f('ix_gsage_email_accounts_org_id'), table_name='gsage_email_accounts')
    op.drop_index(op.f('ix_gsage_email_accounts_email'), table_name='gsage_email_accounts')
    op.drop_index(op.f('ix_gsage_email_accounts_dept_id'), table_name='gsage_email_accounts')
    op.drop_index(op.f('ix_gsage_email_accounts_created_at'), table_name='gsage_email_accounts')
    op.drop_table('gsage_email_accounts')
    op.drop_index(op.f('ix_gsage_data_stores_org_id'), table_name='gsage_data_stores')
    op.drop_index(op.f('ix_gsage_data_stores_is_active'), table_name='gsage_data_stores')
    op.drop_index(op.f('ix_gsage_data_stores_dept_id'), table_name='gsage_data_stores')
    op.drop_index(op.f('ix_gsage_data_stores_created_by'), table_name='gsage_data_stores')
    op.drop_index(op.f('ix_gsage_data_stores_created_at'), table_name='gsage_data_stores')
    op.drop_table('gsage_data_stores')
    op.drop_index(op.f('ix_gsage_approval_delegations_org_id'), table_name='gsage_approval_delegations')
    op.drop_index(op.f('ix_gsage_approval_delegations_dept_id'), table_name='gsage_approval_delegations')
    op.drop_index(op.f('ix_gsage_approval_delegations_created_at'), table_name='gsage_approval_delegations')
    op.drop_index(op.f('ix_gsage_approval_delegations_approver_user_id'), table_name='gsage_approval_delegations')
    op.drop_index(op.f('ix_gsage_approval_delegations_approval_id'), table_name='gsage_approval_delegations')
    op.drop_index('ix_approval_delegation_org', table_name='gsage_approval_delegations')
    op.drop_index('ix_approval_delegation_approver', table_name='gsage_approval_delegations')
    op.drop_table('gsage_approval_delegations')
    op.drop_index(op.f('ix_gsage_api_keys_user_id'), table_name='gsage_api_keys')
    op.drop_index(op.f('ix_gsage_api_keys_org_id'), table_name='gsage_api_keys')
    op.drop_index(op.f('ix_gsage_api_keys_key_prefix'), table_name='gsage_api_keys')
    op.drop_index(op.f('ix_gsage_api_keys_key_hash'), table_name='gsage_api_keys')
    op.drop_index(op.f('ix_gsage_api_keys_dept_id'), table_name='gsage_api_keys')
    op.drop_index(op.f('ix_gsage_api_keys_created_at'), table_name='gsage_api_keys')
    op.drop_table('gsage_api_keys')
    op.drop_index(op.f('ix_gsage_user_organizations_user_id'), table_name='gsage_user_organizations')
    op.drop_index(op.f('ix_gsage_user_organizations_org_id'), table_name='gsage_user_organizations')
    op.drop_index(op.f('ix_gsage_user_organizations_created_at'), table_name='gsage_user_organizations')
    op.drop_table('gsage_user_organizations')
    op.drop_index(op.f('ix_gsage_trusted_devices_user_id'), table_name='gsage_trusted_devices')
    op.drop_index(op.f('ix_gsage_trusted_devices_device_hash'), table_name='gsage_trusted_devices')
    op.drop_index(op.f('ix_gsage_trusted_devices_created_at'), table_name='gsage_trusted_devices')
    op.drop_table('gsage_trusted_devices')
    op.drop_index(op.f('ix_gsage_groups_org_id'), table_name='gsage_groups')
    op.drop_index(op.f('ix_gsage_groups_created_at'), table_name='gsage_groups')
    op.drop_table('gsage_groups')
    op.drop_index(op.f('ix_gsage_departments_org_id'), table_name='gsage_departments')
    op.drop_index(op.f('ix_gsage_departments_is_active'), table_name='gsage_departments')
    op.drop_index(op.f('ix_gsage_departments_created_at'), table_name='gsage_departments')
    op.drop_table('gsage_departments')
    op.drop_index(op.f('ix_gsage_approval_rules_is_active'), table_name='gsage_approval_rules')
    op.drop_index(op.f('ix_gsage_approval_rules_created_at'), table_name='gsage_approval_rules')
    op.drop_index(op.f('ix_gsage_approval_rules_approver_user_id'), table_name='gsage_approval_rules')
    op.drop_index('ix_approval_rule_active', table_name='gsage_approval_rules')
    op.drop_table('gsage_approval_rules')
    op.drop_index(op.f('ix_gsage_users_telegram_id'), table_name='gsage_users')
    op.drop_index(op.f('ix_gsage_users_external_id'), table_name='gsage_users')
    op.drop_index(op.f('ix_gsage_users_email'), table_name='gsage_users')
    op.drop_index(op.f('ix_gsage_users_created_at'), table_name='gsage_users')
    op.drop_table('gsage_users')
    op.drop_index(op.f('ix_gsage_tools_name'), table_name='gsage_tools')
    op.drop_index(op.f('ix_gsage_tools_created_at'), table_name='gsage_tools')
    op.drop_table('gsage_tools')
    op.drop_index('ix_tool_cache_tool_scope', table_name='gsage_tool_cache')
    op.drop_index('ix_tool_cache_org_scope', table_name='gsage_tool_cache')
    op.drop_index('ix_tool_cache_expires_at', table_name='gsage_tool_cache')
    op.drop_index(op.f('ix_gsage_tool_cache_user_id'), table_name='gsage_tool_cache')
    op.drop_index(op.f('ix_gsage_tool_cache_tool_name'), table_name='gsage_tool_cache')
    op.drop_index(op.f('ix_gsage_tool_cache_scope'), table_name='gsage_tool_cache')
    op.drop_index(op.f('ix_gsage_tool_cache_org_id'), table_name='gsage_tool_cache')
    op.drop_index(op.f('ix_gsage_tool_cache_expires_at'), table_name='gsage_tool_cache')
    op.drop_index(op.f('ix_gsage_tool_cache_created_at'), table_name='gsage_tool_cache')
    op.drop_index(op.f('ix_gsage_tool_cache_cache_key'), table_name='gsage_tool_cache')
    op.drop_table('gsage_tool_cache')
    op.drop_index(op.f('ix_gsage_permissions_tag'), table_name='gsage_permissions')
    op.drop_index(op.f('ix_gsage_permissions_created_at'), table_name='gsage_permissions')
    op.drop_table('gsage_permissions')
    op.drop_index(op.f('ix_gsage_organizations_slug'), table_name='gsage_organizations')
    op.drop_index(op.f('ix_gsage_organizations_name'), table_name='gsage_organizations')
    op.drop_index(op.f('ix_gsage_organizations_created_at'), table_name='gsage_organizations')
    op.drop_table('gsage_organizations')
    # ### end Alembic commands ###
