"""email_account_oauth2_fields

Revision ID: 75d2718f51a4
Revises: 519021a00605
Create Date: 2026-04-30 19:28:43.790113

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75d2718f51a4'
down_revision: Union[str, None] = '519021a00605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsage_email_accounts', sa.Column('auth_method', sa.String(length=20), server_default='basic', nullable=False, comment="Authentication mode: 'basic' (LOGIN with password) or 'oauth2' (XOAUTH2 client-credentials)"))
    op.add_column('gsage_email_accounts', sa.Column('oauth_tenant_id', sa.String(length=255), nullable=True, comment='Azure AD tenant ID (UUID) for OAuth2 token endpoint.'))
    op.add_column('gsage_email_accounts', sa.Column('oauth_client_id', sa.String(length=255), nullable=True, comment='Azure AD app client_id (the registered application).'))
    op.add_column('gsage_email_accounts', sa.Column('oauth_client_secret_encrypted', sa.LargeBinary(), nullable=True, comment='AES-256-GCM encrypted OAuth2 client_secret.'))
    op.add_column('gsage_email_accounts', sa.Column('oauth_token_endpoint', sa.String(length=500), nullable=True, comment='Override OAuth2 token endpoint. Defaults to https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token when NULL.'))
    op.add_column('gsage_email_accounts', sa.Column('oauth_scope', sa.String(length=500), nullable=True, comment="OAuth2 scope. Defaults to 'https://outlook.office365.com/.default' when NULL."))
    op.alter_column('gsage_email_accounts', 'imap_password_encrypted',
               existing_type=postgresql.BYTEA(),
               nullable=True,
               comment='AES-256-GCM encrypted IMAP password (NULL for OAuth2 accounts)',
               existing_comment='AES-256-GCM encrypted IMAP password')
    op.create_foreign_key('fk_thread_last_message', 'gsage_email_threads', 'gsage_email_messages', ['last_message_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_thread_first_message', 'gsage_email_threads', 'gsage_email_messages', ['first_message_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_thread_first_message', 'gsage_email_threads', type_='foreignkey')
    op.drop_constraint('fk_thread_last_message', 'gsage_email_threads', type_='foreignkey')
    op.alter_column('gsage_email_accounts', 'imap_password_encrypted',
               existing_type=postgresql.BYTEA(),
               nullable=False,
               comment='AES-256-GCM encrypted IMAP password',
               existing_comment='AES-256-GCM encrypted IMAP password (NULL for OAuth2 accounts)')
    op.drop_column('gsage_email_accounts', 'oauth_scope')
    op.drop_column('gsage_email_accounts', 'oauth_token_endpoint')
    op.drop_column('gsage_email_accounts', 'oauth_client_secret_encrypted')
    op.drop_column('gsage_email_accounts', 'oauth_client_id')
    op.drop_column('gsage_email_accounts', 'oauth_tenant_id')
    op.drop_column('gsage_email_accounts', 'auth_method')
    # ### end Alembic commands ###
