"""add conversation folders

Revision ID: c7010489007b
Revises: e55ab717bfe5
Create Date: 2026-06-11 21:27:15.884580

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7010489007b'
down_revision: Union[str, None] = 'e55ab717bfe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gsage_conversation_folders',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner of the folder. Folders are private to a single user.'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable folder name.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Archive flag. False = archived (hidden by default).'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['gsage_organizations.id'], name=op.f('fk_gsage_conversation_folders_org_id_gsage_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['gsage_users.id'], name=op.f('fk_gsage_conversation_folders_user_id_gsage_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsage_conversation_folders'))
    )
    op.create_index(op.f('ix_gsage_conversation_folders_created_at'), 'gsage_conversation_folders', ['created_at'], unique=False)
    op.create_index(op.f('ix_gsage_conversation_folders_org_id'), 'gsage_conversation_folders', ['org_id'], unique=False)
    op.create_index(op.f('ix_gsage_conversation_folders_user_id'), 'gsage_conversation_folders', ['user_id'], unique=False)
    op.add_column('gsage_tenant_sessions', sa.Column('folder_id', sa.UUID(), nullable=True, comment='Optional folder grouping this conversation. NULL = ungrouped.'))
    op.create_index(op.f('ix_gsage_tenant_sessions_folder_id'), 'gsage_tenant_sessions', ['folder_id'], unique=False)
    op.create_foreign_key(op.f('fk_gsage_tenant_sessions_folder_id_gsage_conversation_folders'), 'gsage_tenant_sessions', 'gsage_conversation_folders', ['folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_gsage_tenant_sessions_folder_id_gsage_conversation_folders'), 'gsage_tenant_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_gsage_tenant_sessions_folder_id'), table_name='gsage_tenant_sessions')
    op.drop_column('gsage_tenant_sessions', 'folder_id')
    op.drop_index(op.f('ix_gsage_conversation_folders_user_id'), table_name='gsage_conversation_folders')
    op.drop_index(op.f('ix_gsage_conversation_folders_org_id'), table_name='gsage_conversation_folders')
    op.drop_index(op.f('ix_gsage_conversation_folders_created_at'), table_name='gsage_conversation_folders')
    op.drop_table('gsage_conversation_folders')
    # ### end Alembic commands ###
