"""teams_channel_fields

Revision ID: 03bdd7da5283
Revises: 75d2718f51a4
Create Date: 2026-04-30 21:39:10.309890

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03bdd7da5283'
down_revision: Union[str, None] = '75d2718f51a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsage_channel_conversations', sa.Column('conversation_reference', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Channel-specific reference for proactive outbound messaging. Currently used by Microsoft Teams to store the Bot Framework ConversationReference.'))
    op.add_column('gsage_users', sa.Column('teams_aad_object_id', sa.String(length=64), nullable=True, comment='Azure AD Object ID (GUID) used to resolve a Teams sender to a GSageUser. Populated either manually by an admin or automatically by the Teams handler on first contact via Microsoft Graph email lookup.'))
    op.create_index(op.f('ix_gsage_users_teams_aad_object_id'), 'gsage_users', ['teams_aad_object_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gsage_users_teams_aad_object_id'), table_name='gsage_users')
    op.drop_column('gsage_users', 'teams_aad_object_id')
    op.drop_column('gsage_channel_conversations', 'conversation_reference')
    # ### end Alembic commands ###
