"""gSage AI — Chat Client API schemas.

These schemas cover:
- Conversation create / list / detail / patch / delete
- Message list and send (sync + SSE stream)
- Programmatic agent run (agents.py)
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Conversations
# ---------------------------------------------------------------------------


class ConversationCreate(BaseModel):
    """Request body for POST /orgs/{org_id}/chat/conversations."""

    title: Optional[str] = Field(default=None, max_length=500)
    agent_id: Optional[str] = Field(
        default="assistant",
        description="Logical agent to attach this conversation to.",
    )


class ConversationPatch(BaseModel):
    """Request body for PATCH /orgs/{org_id}/chat/conversations/{id}."""

    title: Optional[str] = Field(default=None, max_length=500)
    is_active: Optional[bool] = None


class ConversationOut(BaseModel):
    """Response schema for conversation list / detail endpoints."""

    id: uuid.UUID
    agno_session_id: str
    title: Optional[str]
    is_active: bool
    agent_id: Optional[str] = None
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


# ---------------------------------------------------------------------------
# Messages
# ---------------------------------------------------------------------------


class SendMessageRequest(BaseModel):
    """Request body for POST .../conversations/{id}/messages."""

    message: str = Field(..., min_length=1, max_length=32_000)
    attachment_ids: list[uuid.UUID] = Field(
        default_factory=list,
        max_length=10,
        description="UUIDs of files previously uploaded via the attachment endpoint.",
    )


class MessageTokenMetadata(BaseModel):
    input: Optional[int] = None
    output: Optional[int] = None


class MessageMetadata(BaseModel):
    run_id: Optional[str] = None
    model: Optional[str] = None
    tokens: Optional[MessageTokenMetadata] = None
    duration_ms: Optional[int] = None


class MessageOut(BaseModel):
    """A single message in a conversation (from Agno session runs)."""

    id: Optional[str] = None
    role: str  # "user" | "assistant" | "system"
    content: str
    created_at: Optional[datetime] = None
    metadata: Optional[MessageMetadata] = None
    attachments: Optional[list[dict]] = None


class SendMessageResponse(BaseModel):
    """Response for non-streaming POST .../messages.

    When a tool requires human approval the run is paused.  In that case
    ``status`` is ``"pending_approval"``, ``content`` carries a user-visible
    message generated by Agno, ``pending_run_id`` holds the run that must be
    resumed, and ``pending_approvals`` lists the approval IDs that must be
    resolved via ``POST /orgs/{id}/approvals/{id}/resolve`` before the client
    calls ``POST .../messages/continue``.
    """

    id: str
    session_id: str
    agno_session_id: str
    role: str = "assistant"
    content: str
    created_at: datetime
    metadata: MessageMetadata
    # HITL fields — only present when status == "pending_approval"
    status: str = "completed"
    pending_run_id: Optional[str] = None
    pending_approvals: Optional[list[str]] = None


class ContinueRunRequest(BaseModel):
    """Request body for POST .../messages/continue."""

    run_id: str = Field(..., description="The paused run ID returned by the previous send_message call.")


# ---------------------------------------------------------------------------
# Programmatic Agent Run (agents.py)
# ---------------------------------------------------------------------------


class AgentRunRequest(BaseModel):
    """Request body for POST /orgs/{org_id}/agents/{agent_id}/run."""

    message: str = Field(..., min_length=1, max_length=32_000)
    session_id: Optional[str] = Field(
        default=None,
        description=(
            "Existing Agno session ID for continuation. "
            "If omitted a new session scoped to the user is created."
        ),
    )
    stream: bool = Field(default=False, description="Return SSE stream instead of JSON.")


class AgentRunResponse(BaseModel):
    """Response for non-streaming POST /orgs/{org_id}/agents/{agent_id}/run."""

    run_id: Optional[str]
    session_id: str
    agent_id: str
    content: str
    input_tokens: Optional[int] = None
    output_tokens: Optional[int] = None
    duration_ms: Optional[int] = None


# ---------------------------------------------------------------------------
# Agent registry (GET /orgs/{org_id}/agents)
# ---------------------------------------------------------------------------


class AgentInfo(BaseModel):
    """Metadata for a single available agent."""

    id: str
    name: str
    description: str


# ---------------------------------------------------------------------------
# Legacy alias kept for any existing code referencing ChatMessageRequest
# ---------------------------------------------------------------------------


class ChatMessageRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=32_000)
    session_id: Optional[str] = Field(
        default=None,
        description="Existing session ID to continue a conversation; omit to start a new one.",
    )


class ChatMessageResponse(BaseModel):
    session_id: str
    run_id: Optional[str]
    response: str
    input_tokens: Optional[int] = None
    output_tokens: Optional[int] = None
