"""gSage AI — list_recent_artifacts MCP tool.

Lists the most recent files **generated by tools** in the current chat
session (or by the current user when no session is bound).

This is the recovery path when the agent loses the original ``ToolResult``
of a long-running tool call (e.g. ``generate_document`` finishing in the
background after a timeout): the file is still recorded in the database
and can be located by listing recent artifacts.

For chat **attachments** (files uploaded by the user), use ``read_file``
in list mode instead — that helper also exposes the attachment content
when text-based.
"""

from __future__ import annotations

import time
from typing import ClassVar, Optional

from sqlalchemy import select

from src.mcp_server.tools.base import BaseTool, ToolResult
from src.shared.security.context import AgentContext


class ListRecentArtifactsTool(BaseTool):
    """List recent tool-generated files for the current session/user.

    Use this tool to discover files that were produced by other tools
    (``generate_document``, ``zip_tool``, CSV builders, etc.) when the
    original tool result is no longer available — for example because the
    tool ran in the background after a timeout, or because the agent
    needs to reference a file generated earlier in the conversation.

    Filters
    -------
    - ``tool_name``: limit to a specific producer tool (e.g.
      ``"generate_document"``).
    - ``limit``: max rows returned (default 20, max 100).
    - ``include_expired``: when False (default), files past their TTL are
      hidden.

    Scoping
    -------
    Files are scoped to the current chat session when one is bound. When
    no session is available, the user's own recent generated files are
    returned. Other users' files are never visible.

    Use the returned ``file_id`` with ``read_file`` (text content) or
    with the ``download_path`` to retrieve the bytes via the API.

    Permission: ``agents:run``
    """

    name: ClassVar[str] = "list_recent_artifacts"
    version: ClassVar[str] = "1.0.0"
    summary: ClassVar[str] = (
        "List recent files generated by tools in this conversation "
        "(recovery path when a tool result was lost or ran in the background)"
    )
    category: ClassVar[str] = "file"
    core_tool: ClassVar[bool] = True
    permissions: ClassVar[list[str]] = ["agents:run"]
    rate_limit_per_minute: ClassVar[int] = 60
    timeout_seconds: ClassVar[int] = 15
    use_circuit_breaker: ClassVar[bool] = False

    params_schema: ClassVar[dict] = {
        "type": "object",
        "properties": {
            "tool_name": {
                "type": "string",
                "description": (
                    "Optional producer-tool name filter "
                    "(e.g. 'generate_document', 'zip_tool')."
                ),
            },
            "limit": {
                "type": "integer",
                "minimum": 1,
                "maximum": 100,
                "description": "Maximum number of artifacts (default 20).",
            },
            "include_expired": {
                "type": "boolean",
                "description": (
                    "Include files past their TTL. Defaults to False."
                ),
            },
        },
        "required": [],
    }

    async def execute(
        self,
        agent_context: AgentContext,
        params: dict,
        config: dict,
        state: dict,
    ) -> ToolResult:
        from datetime import datetime, timezone  # noqa: PLC0415

        from src.shared.database import _get_session_maker  # noqa: PLC0415
        from src.shared.models.generated_file import GSageFile  # noqa: PLC0415
        from src.mcp_server.tenant_context import (  # noqa: PLC0415
            get_tenant_headers_or_none,
        )

        t0 = time.monotonic()

        tool_filter: Optional[str] = params.get("tool_name") or None
        limit = min(int(params.get("limit") or 20), 100)
        include_expired = bool(params.get("include_expired") or False)

        tenant = get_tenant_headers_or_none()
        session_id = tenant.gsage_session_id if tenant else None

        async with _get_session_maker()() as db:
            stmt = (
                select(GSageFile)
                .where(
                    GSageFile.org_id == agent_context.org_id,
                    GSageFile.category == "generated",
                    GSageFile.purged_at.is_(None),
                )
            )
            if session_id:
                stmt = stmt.where(GSageFile.session_id == session_id)
            else:
                stmt = stmt.where(GSageFile.user_id == agent_context.user_id)

            if tool_filter:
                stmt = stmt.where(GSageFile.tool_name == tool_filter)

            if not include_expired:
                now = datetime.now(timezone.utc)
                stmt = stmt.where(
                    (GSageFile.expires_at.is_(None))
                    | (GSageFile.expires_at > now)
                )

            stmt = stmt.order_by(GSageFile.created_at.desc()).limit(limit)
            rows = (await db.execute(stmt)).scalars().all()

        artifacts = [
            {
                "file_id": str(row.id),
                "filename": row.filename,
                "content_type": row.content_type,
                "size_bytes": row.size_bytes,
                "tool_name": row.tool_name,
                "trace_id": row.trace_id,
                "description": row.description,
                "created_at": (
                    row.created_at.isoformat() if row.created_at else None
                ),
                "expires_at": (
                    row.expires_at.isoformat() if row.expires_at else None
                ),
                "download_path": (
                    f"/v1/orgs/{agent_context.org_id}/files/{row.id}/download"
                ),
            }
            for row in rows
        ]

        return ToolResult.success(
            data={
                "artifacts": artifacts,
                "count": len(artifacts),
                "session_scoped": bool(session_id),
                "filtered_by_tool": tool_filter,
            },
            tool_name=self.name,
            version=self.version,
            execution_time_ms=int((time.monotonic() - t0) * 1000),
        )
