"""Curator — high-performance collection dump to /data/.

Uses PostgreSQL ``COPY (SELECT ...) TO STDOUT`` via asyncpg raw connections
to stream list data directly to disk without creating Python objects per row.
Handles millions of entries efficiently.

State machine integration:
    - Called by the background dump task after WAIT_TIME expires.
    - Sets collection status to ``processing`` before writing.
    - Uses atomic writes (temp file → os.replace) to avoid serving partial files.
    - After writing, checks whether new items were inserted during the dump;
      if so, transitions back to ``waiting`` and re-queues the dump task.
"""

from __future__ import annotations

import asyncio
import logging
import os
from datetime import datetime, timezone
from pathlib import Path

from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from .config import get_settings
from .database import get_engine, get_session_factory
from .models import Collection, Item, ITEM_TYPES

log = logging.getLogger(__name__)

# Guards against concurrent dump tasks per collection
_dump_locks: dict[int, asyncio.Lock] = {}


def _get_lock(collection_id: int) -> asyncio.Lock:
    if collection_id not in _dump_locks:
        _dump_locks[collection_id] = asyncio.Lock()
    return _dump_locks[collection_id]


# ── COPY queries ──────────────────────────────────────────────────────────────
# asyncpg copy_from_query() takes a plain SELECT — it wraps it in COPY internally.

_PLAIN_QUERY = """
SELECT COALESCE(host(cidr), value)
FROM curator_items
WHERE collection_id = {cid}
  AND type = '{itype}'
  AND deleted_at IS NULL
  AND (expire_at IS NULL OR expire_at > NOW())
ORDER BY id
""".strip()

_META_QUERY = """
SELECT
    COALESCE(host(cidr), value)
    || ' # '
    || TO_CHAR(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD')
    || ' '
    || COALESCE(TO_CHAR(expire_at AT TIME ZONE 'UTC', 'YYYY-MM-DD'), 'never')
    || ' '
    || COALESCE(public_reference, '')
FROM curator_items
WHERE collection_id = {cid}
  AND type = '{itype}'
  AND deleted_at IS NULL
  AND (expire_at IS NULL OR expire_at > NOW())
ORDER BY id
""".strip()


async def _copy_to_file(asyncpg_conn, query: str, dest: Path) -> int:
    """Stream COPY output to *dest* atomically.  Returns row count."""
    tmp = dest.with_suffix(".tmp")
    dest.parent.mkdir(parents=True, exist_ok=True)
    try:
        status = await asyncpg_conn.copy_from_query(query, output=str(tmp))
        # status string is e.g. "COPY 12345"
        rows = int(status.split()[-1]) if status else 0
        if rows > 0:
            os.replace(tmp, dest)
        else:
            tmp.unlink(missing_ok=True)
    except Exception:
        tmp.unlink(missing_ok=True)
        raise
    return rows


async def _write_readme(collection: Collection, slug_dir: Path) -> None:
    lines = [
        f"Collection: {collection.short_description}",
        f"Type: {collection.type}" + (f"  Subtype: {collection.subtype}" if collection.subtype else ""),
        f"Slug: {collection.slug}",
        "",
    ]
    if collection.description:
        lines += [collection.description, ""]

    lines += [
        "File format",
        "-----------",
        f"  {collection.type}_<list_type>.txt          — one entry per line",
        f"  {collection.type}_<list_type>_metadata.txt — entry # created_date expire_date public_reference",
        "  lastupdated                             — ISO 8601 timestamp of last dump",
        "",
        "List types: blocklist, allowlist, suspected",
        "",
        "Differentials",
        "-------------",
        "  differentials/YYYY/MM/DD/<file>.txt  — per-day '+ added' / '- removed' diff",
        "  differentials/YYYY/MM/<file>.txt     — monthly net-change diff",
        "  Files are generated lazily on first HTTP request and cached on disk.",
        "",
        "Generated by Curator.",
    ]
    readme = slug_dir / "00-README.txt"
    tmp = readme.with_suffix(".tmp")
    tmp.write_text("\n".join(lines), encoding="utf-8")
    os.replace(tmp, readme)


async def dump_collection(collection_id: int) -> None:
    """Full dump lifecycle for one collection.

    Acquires a per-collection lock so concurrent triggers are serialised.
    """
    lock = _get_lock(collection_id)
    async with lock:
        await _do_dump(collection_id)


async def _do_dump(collection_id: int) -> None:
    settings = get_settings()
    factory = get_session_factory()
    engine = get_engine()

    async with factory() as session:
        collection = await session.get(Collection, collection_id)
        if collection is None:
            log.warning("dump: collection %s not found, skipping", collection_id)
            return
        if not collection.active:
            log.info("dump: collection %s is inactive, skipping", collection_id)
            # Reset to idle so it can be reactivated later
            collection.status = "idle"
            await session.commit()
            return

        # Mark as processing and record the start time (to detect new items)
        dump_started_at = datetime.now(tz=timezone.utc)
        collection.status = "processing"
        collection.touch()
        await session.commit()
        log.info("dump: starting for collection %s (%s)", collection_id, collection.slug)

    slug_dir = Path(settings.data_dir) / collection.slug
    collection_slug = collection.slug  # capture before re-fetches may reassign

    try:
        # Acquire a raw asyncpg connection for COPY via SQLAlchemy async connect
        async with engine.connect() as conn:
            raw = await conn.get_raw_connection()
            asyncpg_conn = raw.driver_connection  # actual asyncpg Connection

            for item_type in ITEM_TYPES:
                plain_file = slug_dir / f"{collection.type}_{item_type}.txt"
                meta_file = slug_dir / f"{collection.type}_{item_type}_metadata.txt"

                plain_q = _PLAIN_QUERY.format(cid=collection_id, itype=item_type)
                meta_q = _META_QUERY.format(cid=collection_id, itype=item_type)

                rows = await _copy_to_file(asyncpg_conn, plain_q, plain_file)
                await _copy_to_file(asyncpg_conn, meta_q, meta_file)

                # Remove empty files
                if rows == 0:
                    plain_file.unlink(missing_ok=True)
                    meta_file.unlink(missing_ok=True)

        # Write README and timestamp
        async with factory() as session:
            coll_for_readme = await session.get(Collection, collection_id)
            if coll_for_readme:
                await _write_readme(coll_for_readme, slug_dir)

        ts_file = slug_dir / "lastupdated"
        tmp_ts = ts_file.with_suffix(".tmp")
        tmp_ts.write_text(dump_started_at.isoformat(), encoding="utf-8")
        os.replace(tmp_ts, ts_file)

        log.info("dump: completed for collection %s (%s)", collection_id, collection_slug)

    except Exception:
        log.exception("dump: error for collection %s", collection_id)
        # Restore to waiting so the next add_item will re-trigger
        async with factory() as session:
            c = await session.get(Collection, collection_id)
            if c:
                c.status = "waiting"
                c.touch()
                await session.commit()
        return

    # Check whether new items arrived while we were dumping
    async with factory() as session:
        c = await session.get(Collection, collection_id)
        if c is None:
            return

        # Count items created after dump started (i.e. added during processing)
        result = await session.execute(
            select(Item.id)
            .where(Item.collection_id == collection_id)
            .where(Item.created_at > dump_started_at)
            .limit(1)
        )
        has_new = result.first() is not None

        if has_new:
            log.info("dump: new items arrived during dump for collection %s, re-queuing", collection_id)
            c.status = "waiting"
        else:
            c.status = "idle"
        c.touch()
        await session.commit()

    if has_new:
        # Re-schedule after WAIT_TIME
        asyncio.get_event_loop().call_later(
            get_settings().wait_time,
            lambda: asyncio.ensure_future(dump_collection(collection_id)),
        )


async def schedule_dump(collection_id: int) -> None:
    """Schedule a dump after WAIT_TIME seconds (non-blocking)."""
    wait = get_settings().wait_time

    async def _delayed():
        await asyncio.sleep(wait)
        await dump_collection(collection_id)

    asyncio.ensure_future(_delayed())
