"""gSage AI — GSageFile model.

Tracks files generated by MCP tools and stored in MinIO.

Lifecycle
---------
1. Tool calls ``BaseTool._store_file()`` → uploads bytes to MinIO and
   inserts a row here with ``expires_at`` set.
2. The Celery ``purge_expired_files`` task runs hourly:
   - Deletes the MinIO object (bytes gone).
   - Sets ``purged_at`` on the row (record stays forever for audit).
3. After purging, presigned URL requests return 404/410 because the object
   no longer exists in MinIO.

Storage key convention
----------------------
``{org_id}/{user_id}/{file_id}``  (all UUIDs, no file extension in key —
the original filename is stored in ``filename``).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import DateTime, ForeignKey, Index, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from src.shared.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin


class GSageFile(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """A file generated by a tool and stored in MinIO.

    Columns
    -------
    org_id
        Owning organisation.
    user_id
        User whose agent produced this file.
    tool_name
        Name of the tool that created this file (e.g. "pdf_report").
    trace_id
        Optional: Agno run/trace ID that produced this file — useful for
        correlating with agent traces in Elasticsearch.
    filename
        Original filename as shown to the user (e.g. "report-2026-04.pdf").
    content_type
        MIME type (e.g. "application/pdf", "text/csv").
    size_bytes
        File size in bytes.
    storage_key
        Full object key in MinIO bucket (``{org_id}/{user_id}/{file_id}``).
    description
        Optional human-readable description produced by the tool.
    expires_at
        UTC datetime when this file should be purged.  NULL = never expires.
    purged_at
        Set when the Celery task successfully deleted the MinIO object.
        NULL means the bytes are still accessible.  The row is never deleted.
    """

    __tablename__ = "gsage_files"

    org_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("gsage_organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    dept_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("gsage_departments.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="Department context when this file was generated.",
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("gsage_users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    tool_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True,
    )
    trace_id: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
        index=True,
        comment="Agno run/trace ID that produced this file",
    )
    filename: Mapped[str] = mapped_column(
        String(512),
        nullable=False,
        comment="Original filename shown to the user",
    )
    content_type: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
        default="application/octet-stream",
    )
    size_bytes: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )
    storage_key: Mapped[str] = mapped_column(
        String(512),
        nullable=False,
        comment="Full object key in MinIO bucket",
    )
    description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="Human-readable description produced by the tool",
    )
    expires_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
        comment="UTC datetime when this file should be purged. NULL = never.",
    )
    purged_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
        comment="Set when the Celery purge task deleted the MinIO object.",
    )
    category: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="generated",
        server_default="generated",
        index=True,
        comment="'generated' = tool output, 'template' = user-uploaded document, 'attachment' = chat message attachment",
    )
    scope: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="user",
        server_default="user",
        index=True,
        comment="'user' = private to uploader, 'department' = visible to all department members, 'organization' = visible to all org members",
    )
    session_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("gsage_tenant_sessions.id", ondelete="SET NULL"),
        nullable=True,
        comment="Chat session this attachment belongs to. NULL for generated/template files.",
    )

    __table_args__ = (
        Index("ix_gsage_files_org_expires", "org_id", "expires_at"),
        Index("ix_gsage_files_org_category", "org_id", "category"),
        Index("ix_gsage_files_session", "session_id"),
    )
