#!/usr/bin/env python3
"""Generate operator-facing Markdown documentation for every MCP tool.

This script introspects each registered ``BaseTool`` subclass, groups
tools by ``config_namespace`` (or by tool name for singletons), and
overwrites Markdown files under ``docs/tools/`` plus a derived
``.env.tools.example`` listing every configuration-derived environment
variable.

The source of truth is the tool ``.py`` files (ClassVars, schemas,
docstrings).  The output is auto-generated and **must not be edited by
hand** — the banner at the top of every file states this explicitly.

Usage::

    python scripts/generate_tools_docs.py
    python scripts/generate_tools_docs.py --actions-depth medium
    python scripts/generate_tools_docs.py --check    # exit 1 on diff
    python scripts/generate_tools_docs.py --only "trellix.*"

The script is idempotent — running twice in a row produces zero diff.
"""

from __future__ import annotations

import argparse
import ast
import inspect
import json
import re
import sys
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

# Reuse the existing discovery helper rather than duplicating the
# pkgutil walker — it already handles graceful import failures.
from scripts.generate_env_defaults import discover_tools  # noqa: E402

TOOLS_PACKAGE = "src.mcp_server.tools"
TOOLS_PATH = ROOT / "src" / "mcp_server" / "tools"

DEFAULT_OUTPUT_DIR = ROOT / "docs" / "tools"
DEFAULT_ENV_FILE = ROOT / ".env.tools.example"

AUTOGEN_BANNER = (
    "<!-- AUTO-GENERATED by scripts/generate_tools_docs.py — do not edit manually. -->\n"
    "<!-- Source of truth: the tool's Python source file(s) listed at the bottom. -->\n"
)

ENV_FILE_BANNER = (
    "# AUTO-GENERATED by scripts/generate_tools_docs.py — do not edit manually.\n"
    "# Derived from each tool's `config_schema` / `config_defaults`.\n"
    "# Fill in the values that apply to your deployment in your real `.env`.\n"
    "#\n"
    "# Sensitive fields are emitted with a placeholder `__SET_ME__`. NEVER commit\n"
    "# real secrets to git — use `.env`, a secret manager, or per-org DB config.\n"
    "#\n"
    "# Resolution order (lowest → highest precedence):\n"
    "#   1. config_defaults (hardcoded)\n"
    "#   2. environment variables (this file)\n"
    "#   3. per-org DB config (web UI configtool, encrypted)\n"
    "#   4. per-profile override (when supports_multiple_configs=true)\n"
    "#\n"
)


# ──────────────────────────────────────────────────────────────────────
# Data model
# ──────────────────────────────────────────────────────────────────────


@dataclass
class ToolInfo:
    """Snapshot of a tool's relevant ClassVars and source paths."""

    cls: type
    name: str
    version: str
    summary: str
    category: str
    permissions: list[str]
    requires_approval: bool
    requires_config: bool
    core_tool: bool
    available: bool
    rate_limit_per_minute: int
    timeout_seconds: int
    use_circuit_breaker: bool
    always_background: bool
    background_threshold_seconds: Optional[int]
    supports_multiple_configs: bool
    config_namespace: Optional[str]
    config_schema: Optional[dict]
    config_defaults: dict
    state_schema: Optional[dict]
    state_defaults: dict
    reset_policy: str
    params_schema: Optional[dict]
    module_doc: Optional[str]
    class_doc: Optional[str]
    source_file: Path
    source_rel: str  # relative to repo root, e.g. src/mcp_server/tools/...

    @classmethod
    def from_class(cls, tool_cls: type) -> "ToolInfo":
        try:
            src = inspect.getsourcefile(tool_cls) or ""
        except TypeError:
            src = ""
        source_file = Path(src) if src else Path()
        try:
            source_rel = str(source_file.resolve().relative_to(ROOT))
        except (ValueError, OSError):
            source_rel = src

        module = inspect.getmodule(tool_cls)
        module_doc = inspect.getdoc(module) if module else None
        class_doc = inspect.getdoc(tool_cls)

        # ClassVars: read with ``getattr`` so we honour inherited defaults.
        return cls(
            cls=tool_cls,
            name=getattr(tool_cls, "name", tool_cls.__name__),
            version=getattr(tool_cls, "version", "1.0.0"),
            summary=getattr(tool_cls, "summary", "") or "",
            category=getattr(tool_cls, "category", "general"),
            permissions=list(getattr(tool_cls, "permissions", []) or []),
            requires_approval=bool(getattr(tool_cls, "requires_approval", False)),
            requires_config=bool(getattr(tool_cls, "requires_config", False)),
            core_tool=bool(getattr(tool_cls, "core_tool", False)),
            available=bool(getattr(tool_cls, "available", True)),
            rate_limit_per_minute=int(getattr(tool_cls, "rate_limit_per_minute", 60)),
            timeout_seconds=int(getattr(tool_cls, "timeout_seconds", 30)),
            use_circuit_breaker=bool(getattr(tool_cls, "use_circuit_breaker", True)),
            always_background=bool(getattr(tool_cls, "always_background", False)),
            background_threshold_seconds=getattr(
                tool_cls, "background_threshold_seconds", None
            ),
            supports_multiple_configs=bool(
                getattr(tool_cls, "supports_multiple_configs", False)
            ),
            config_namespace=getattr(tool_cls, "config_namespace", None),
            config_schema=getattr(tool_cls, "config_schema", None),
            config_defaults=dict(getattr(tool_cls, "config_defaults", {}) or {}),
            state_schema=getattr(tool_cls, "state_schema", None),
            state_defaults=dict(getattr(tool_cls, "state_defaults", {}) or {}),
            reset_policy=getattr(tool_cls, "reset_policy", "never"),
            params_schema=getattr(tool_cls, "params_schema", None),
            module_doc=module_doc,
            class_doc=class_doc,
            source_file=source_file,
            source_rel=source_rel,
        )

    @property
    def has_config(self) -> bool:
        return bool(self.config_schema) or bool(self.config_defaults)


@dataclass
class ToolGroup:
    """A namespace group (≥1 tool) or a singleton tool."""

    group_id: str  # namespace if shared, else tool name
    namespace: Optional[str]  # None for singletons without namespace
    tools: list[ToolInfo] = field(default_factory=list)

    @property
    def is_family(self) -> bool:
        return len(self.tools) > 1

    @property
    def display_title(self) -> str:
        if self.namespace and self.is_family:
            pretty = self.namespace.replace("_", " ").title()
            return f"{pretty} Tools"
        if len(self.tools) == 1:
            t = self.tools[0]
            pretty = t.name.replace("_", " ").title()
            return pretty
        return self.group_id


# ──────────────────────────────────────────────────────────────────────
# Grouping & output paths
# ──────────────────────────────────────────────────────────────────────


def group_tools(tools: list[ToolInfo]) -> list[ToolGroup]:
    """Group tools by ``config_namespace``; singletons keep their own group."""
    groups: dict[str, ToolGroup] = {}
    for t in tools:
        if t.config_namespace:
            key = t.config_namespace
            grp = groups.setdefault(
                key, ToolGroup(group_id=key, namespace=key)
            )
        else:
            key = f"__single__::{t.name}"
            grp = groups.setdefault(
                key, ToolGroup(group_id=t.name, namespace=None)
            )
        grp.tools.append(t)

    # Stable internal ordering.
    for grp in groups.values():
        grp.tools.sort(key=lambda x: x.name)

    return sorted(groups.values(), key=lambda g: (g.namespace or g.group_id))


def output_path_for(group: ToolGroup, output_dir: Path) -> Path:
    """Compute the Markdown output path for a group.

    Rules:
      - If ≥2 tools share the same source directory under
        ``src/mcp_server/tools/`` → ``<parent>/<dir_name>.md``.
      - Otherwise (singleton) → ``<dir>/<tool_filename_stem>.md``.
    """
    sources = [Path(t.source_rel) for t in group.tools if t.source_rel]
    if not sources:
        return output_dir / f"{group.group_id}.md"

    # Strip the prefix `src/mcp_server/tools/` to get a tools-relative path.
    rel_paths: list[Path] = []
    prefix = Path("src/mcp_server/tools")
    for s in sources:
        try:
            rel_paths.append(s.relative_to(prefix))
        except ValueError:
            rel_paths.append(s)

    # All tool dirs (parent of each .py).
    dirs = {p.parent for p in rel_paths}

    if len(rel_paths) >= 2 and len(dirs) == 1:
        # Family living together in one folder. Promote one level up only
        # when the folder name matches the namespace (or group id) — this
        # avoids generating ambiguous files like ``core.md`` for a family
        # that simply happens to share the ``core/`` directory.
        only_dir = next(iter(dirs))
        if str(only_dir) in (".", ""):
            return output_dir / f"{group.group_id}.md"
        if only_dir.name in {group.namespace, group.group_id}:
            return output_dir / only_dir.parent / f"{only_dir.name}.md"
        # Folder name doesn't match the family — keep the file inside the
        # folder, named after the namespace / group id.
        return output_dir / only_dir / f"{group.group_id}.md"

    # Singleton (or split family): doc next to the first source file.
    stem = rel_paths[0].stem if not group.is_family else group.group_id
    return output_dir / rel_paths[0].parent / f"{stem}.md"


# ──────────────────────────────────────────────────────────────────────
# Schema helpers
# ──────────────────────────────────────────────────────────────────────


def schema_properties(schema: Optional[dict]) -> dict[str, dict]:
    """Return the JSON-Schema-style properties map (handles flat fallback)."""
    if not schema:
        return {}
    if "properties" in schema and isinstance(schema["properties"], dict):
        return schema["properties"]
    # Flat: top-level keys ARE the fields (legacy form). Skip JSON-Schema meta.
    meta = {"type", "required", "additionalProperties", "description", "title"}
    out: dict[str, dict] = {}
    for k, v in schema.items():
        if k in meta or not isinstance(v, dict):
            continue
        out[k] = v
    return out


def required_fields(schema: Optional[dict]) -> list[str]:
    if not schema:
        return []
    req = schema.get("required") if isinstance(schema, dict) else None
    return list(req) if isinstance(req, list) else []


def merge_schemas(tools: list[ToolInfo]) -> tuple[dict[str, dict], list[str], dict[str, Any]]:
    """Merge ``config_schema`` / ``config_defaults`` across a tool family.

    Tools sharing a ``config_namespace`` typically have identical config
    surfaces (same client, same credentials).  Where they differ, we take
    the union and the first non-empty value wins for descriptions /
    defaults — matching the resolution rule used by ``base.py``.
    """
    props: dict[str, dict] = {}
    required: list[str] = []
    defaults: dict[str, Any] = {}
    for t in tools:
        for fname, finfo in schema_properties(t.config_schema).items():
            if fname not in props and isinstance(finfo, dict):
                props[fname] = dict(finfo)
        for r in required_fields(t.config_schema):
            if r not in required:
                required.append(r)
        for fname, fval in t.config_defaults.items():
            defaults.setdefault(fname, fval)
    return props, required, defaults


def field_default(props: dict[str, dict], defaults: dict, fname: str) -> Any:
    """Return the most authoritative default for a field, if any."""
    schema_default = props.get(fname, {}).get("default")
    if schema_default is not None:
        return schema_default
    return defaults.get(fname)


# ──────────────────────────────────────────────────────────────────────
# Env-var name derivation
# ──────────────────────────────────────────────────────────────────────


def env_var_name(scope: str, field_name: str) -> str:
    """Build the canonical ``TOOL_{SCOPE}__{FIELD}`` env var name.

    Mirrors ``BaseTool._load_env_defaults`` in ``src/mcp_server/tools/base.py``.
    """
    return f"TOOL_{scope.upper()}__{field_name.upper()}"


# Loose env-var scan (AST) — pick up calls like ``os.environ.get("FOO", ...)``,
# ``os.getenv("FOO", ...)`` and subscripts ``os.environ["FOO"]``.

_OS_NAMES = {"os"}


def _string_const(node: ast.AST) -> Optional[str]:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


def scan_loose_env_vars(source_files: list[Path]) -> list[tuple[str, Optional[str]]]:
    """Return a sorted, deduplicated list of ``(name, default)`` env reads."""
    found: dict[str, Optional[str]] = {}
    for fpath in source_files:
        try:
            text = fpath.read_text(encoding="utf-8", errors="replace")
            tree = ast.parse(text)
        except Exception:
            continue
        for node in ast.walk(tree):
            # os.environ.get("FOO"[, default]) and os.getenv("FOO"[, default])
            if isinstance(node, ast.Call):
                func = node.func
                target: Optional[str] = None
                if (
                    isinstance(func, ast.Attribute)
                    and isinstance(func.value, ast.Attribute)
                    and isinstance(func.value.value, ast.Name)
                    and func.value.value.id in _OS_NAMES
                    and func.value.attr == "environ"
                    and func.attr == "get"
                ):
                    target = "os.environ.get"
                elif (
                    isinstance(func, ast.Attribute)
                    and isinstance(func.value, ast.Name)
                    and func.value.id in _OS_NAMES
                    and func.attr == "getenv"
                ):
                    target = "os.getenv"
                if target and node.args:
                    name = _string_const(node.args[0])
                    if not name:
                        continue
                    default_val: Optional[str] = None
                    if len(node.args) >= 2:
                        c = _string_const(node.args[1])
                        if c is not None:
                            default_val = c
                    # Skip TOOL_*__* — those are config-derived and already
                    # rendered in the env table.
                    if name.startswith("TOOL_") and "__" in name:
                        continue
                    found.setdefault(name, default_val)
            # os.environ["FOO"]
            if isinstance(node, ast.Subscript):
                value = node.value
                if (
                    isinstance(value, ast.Attribute)
                    and isinstance(value.value, ast.Name)
                    and value.value.id in _OS_NAMES
                    and value.attr == "environ"
                ):
                    key_node = node.slice
                    name = _string_const(key_node)
                    if name and not (name.startswith("TOOL_") and "__" in name):
                        found.setdefault(name, None)
    return sorted(found.items(), key=lambda kv: kv[0])


# ──────────────────────────────────────────────────────────────────────
# Markdown rendering — small helpers
# ──────────────────────────────────────────────────────────────────────


def md_escape_cell(value: str) -> str:
    """Escape pipes and newlines so Markdown table cells survive."""
    return value.replace("\n", " ").replace("|", "\\|").strip()


def md_bool(value: bool) -> str:
    return "✓" if value else "—"


def md_link(rel_path: str) -> str:
    return f"[{rel_path}]({rel_path})"


def first_paragraph(text: Optional[str]) -> str:
    if not text:
        return ""
    for chunk in text.strip().split("\n\n"):
        cleaned = chunk.strip()
        if cleaned:
            return cleaned
    return text.strip()


def schema_type(field_info: dict) -> str:
    t = field_info.get("type")
    if isinstance(t, list):
        return " | ".join(str(x) for x in t)
    if isinstance(t, str):
        return t
    if "enum" in field_info:
        vals = field_info.get("enum") or []
        return f"enum({', '.join(repr(v) for v in vals)})"
    return "—"


# ──────────────────────────────────────────────────────────────────────
# Markdown rendering — sections
# ──────────────────────────────────────────────────────────────────────


def render_overview(group: ToolGroup) -> str:
    """Pick a "primary" tool's docstring as the group overview."""
    primary = next(
        (t for t in group.tools if t.name == group.group_id),
        group.tools[0],
    )
    text = primary.module_doc or primary.class_doc or ""
    para = first_paragraph(text)
    return para or "_No description provided._"


def render_tools_table(group: ToolGroup) -> str:
    rows: list[str] = [
        "| Tool | Summary | Permissions | Requires approval | Core |",
        "| --- | --- | --- | :---: | :---: |",
    ]
    for t in group.tools:
        perms = ", ".join(f"`{p}`" for p in t.permissions) or "—"
        rows.append(
            "| `{name}` | {summary} | {perms} | {appr} | {core} |".format(
                name=md_escape_cell(t.name),
                summary=md_escape_cell(t.summary or first_paragraph(t.class_doc) or "—"),
                perms=md_escape_cell(perms),
                appr=md_bool(t.requires_approval),
                core=md_bool(t.core_tool),
            )
        )
    return "\n".join(rows)


def render_config_skeleton(
    props: dict[str, dict], required: list[str], defaults: dict
) -> str:
    """Minimal JSON skeleton for the configtool.  Sensitive fields are omitted."""
    skeleton: dict[str, Any] = {}
    for fname in required:
        finfo = props.get(fname, {})
        if finfo.get("sensitive"):
            continue
        default = field_default(props, defaults, fname)
        skeleton[fname] = default if default is not None else _placeholder_for(finfo)
    if not skeleton:
        return "{}"
    return json.dumps(skeleton, indent=2, ensure_ascii=False)


def render_config_example(props: dict[str, dict], defaults: dict) -> str:
    """Example JSON with placeholders for every (non-sensitive) field."""
    payload: dict[str, Any] = {}
    for fname in sorted(props.keys()):
        finfo = props[fname]
        if finfo.get("sensitive"):
            # Sensitive fields go through env vars, not the JSON.
            continue
        default = field_default(props, defaults, fname)
        payload[fname] = default if default is not None else _placeholder_for(finfo)
    if not payload:
        return "{}"
    return json.dumps(payload, indent=2, ensure_ascii=False)


def _placeholder_for(finfo: dict) -> Any:
    t = finfo.get("type")
    if t == "boolean":
        return False
    if t == "integer":
        return 0
    if t == "number":
        return 0.0
    if t == "array":
        return []
    if t == "object":
        return {}
    enum_vals = finfo.get("enum")
    if enum_vals:
        return enum_vals[0]
    return "<value>"


def render_field_reference(
    props: dict[str, dict], required: list[str], defaults: dict
) -> str:
    rows = [
        "| Field | Type | Required | Sensitive | Default | Description |",
        "| --- | --- | :---: | :---: | --- | --- |",
    ]
    for fname in sorted(props.keys()):
        finfo = props[fname]
        default = field_default(props, defaults, fname)
        default_repr = (
            "—" if default is None else f"`{json.dumps(default, ensure_ascii=False)}`"
        )
        if finfo.get("sensitive"):
            default_repr = "—"
        rows.append(
            "| `{f}` | `{t}` | {req} | {sens} | {default} | {desc} |".format(
                f=md_escape_cell(fname),
                t=md_escape_cell(schema_type(finfo)),
                req=md_bool(fname in required),
                sens=md_bool(bool(finfo.get("sensitive"))),
                default=md_escape_cell(default_repr),
                desc=md_escape_cell(finfo.get("description") or "—"),
            )
        )
    return "\n".join(rows)


def render_env_table(group: ToolGroup) -> str:
    """Render the canonical config-derived env-var table for a group.

    Layout:
      - Rows under ``TOOL_{NAMESPACE}__*`` when the group has a namespace.
      - Rows under ``TOOL_{TOOL_NAME}__*`` for tool-specific overrides
        (only fields the tool exposes that are not part of the shared
        namespace surface — useful for legacy singletons too).
    """
    rows = [
        "| Variable | Maps to field | Type | Default | Sensitive | Description |",
        "| --- | --- | --- | --- | :---: | --- |",
    ]
    seen_vars: set[str] = set()
    namespace_fields: set[str] = set()

    if group.namespace and group.is_family:
        ns_props, ns_required, ns_defaults = merge_schemas(group.tools)
        namespace_fields = set(ns_props.keys())
        for fname in sorted(ns_props.keys()):
            finfo = ns_props[fname]
            var = env_var_name(group.namespace, fname)
            seen_vars.add(var)
            default = field_default(ns_props, ns_defaults, fname)
            default_repr = (
                "—"
                if default is None or finfo.get("sensitive")
                else f"`{json.dumps(default, ensure_ascii=False)}`"
            )
            rows.append(
                "| `{v}` | `{f}` | `{t}` | {d} | {s} | {desc} |".format(
                    v=var,
                    f=md_escape_cell(fname),
                    t=md_escape_cell(schema_type(finfo)),
                    d=md_escape_cell(default_repr),
                    s=md_bool(bool(finfo.get("sensitive"))),
                    desc=md_escape_cell(finfo.get("description") or "—"),
                )
            )

    for t in group.tools:
        scope = t.name
        if t.config_namespace and t.config_namespace == t.name:
            continue
        props = schema_properties(t.config_schema)
        if not props and not t.config_defaults:
            continue
        for fname in sorted(props.keys() | t.config_defaults.keys()):
            # When the field is already represented by the shared namespace
            # variable, do NOT also emit the per-tool override row — every
            # field accepts a per-tool override implicitly.
            if fname in namespace_fields:
                continue
            finfo = props.get(fname, {})
            var = env_var_name(scope, fname)
            if var in seen_vars:
                continue
            seen_vars.add(var)
            default = field_default(props, t.config_defaults, fname)
            default_repr = (
                "—"
                if default is None or finfo.get("sensitive")
                else f"`{json.dumps(default, ensure_ascii=False)}`"
            )
            rows.append(
                "| `{v}` | `{f}` | `{t}` | {d} | {s} | {desc} |".format(
                    v=var,
                    f=md_escape_cell(fname),
                    t=md_escape_cell(schema_type(finfo)),
                    d=md_escape_cell(default_repr),
                    s=md_bool(bool(finfo.get("sensitive"))),
                    desc=md_escape_cell(finfo.get("description") or "—"),
                )
            )
    if len(rows) == 2:
        return "_No configuration-derived environment variables._"
    note = (
        "\n\n_Note: any field above can also be overridden per-tool by "
        "using the prefix `TOOL_<TOOL_NAME>__` instead of the shared "
        "`TOOL_<NAMESPACE>__` — useful when a single tool in the family "
        "needs a distinct value._"
        if group.namespace and group.is_family
        else ""
    )
    return "\n".join(rows) + note


def render_loose_env_table(group: ToolGroup) -> str:
    sources = [t.source_file for t in group.tools if t.source_file.exists()]
    pairs = scan_loose_env_vars(sources)
    if not pairs:
        return ""
    rows = [
        "",
        "**Other environment variables** (read directly from the source — not part of `config_schema`):",
        "",
        "| Variable | Default in code |",
        "| --- | --- |",
    ]
    for name, default in pairs:
        d_repr = (
            "—"
            if default is None
            else f"`{json.dumps(default, ensure_ascii=False)}`"
        )
        rows.append(f"| `{name}` | {d_repr} |")
    return "\n".join(rows)


def render_actions_section(t: ToolInfo, depth: str) -> str:
    """Render the action / operations block for a tool.

    A tool is considered "action-driven" when its ``params_schema`` has a
    top-level ``properties.action.enum`` list.
    """
    schema = t.params_schema or {}
    props = schema.get("properties") if isinstance(schema, dict) else None
    if not isinstance(props, dict):
        return ""
    action_def = props.get("action")
    if not isinstance(action_def, dict):
        return ""
    enum = action_def.get("enum")
    if not isinstance(enum, list) or not enum:
        return ""

    raw_desc = action_def.get("description") or ""
    per_action = _split_action_descriptions(raw_desc, enum)

    lines: list[str] = []
    for value in enum:
        lines.append(f"- **`{value}`** — {per_action.get(value, '_(no description)_')}")
        if depth == "medium":
            relevant = _params_for_action(props, value, raw_desc)
            if relevant:
                lines.append("")
                lines.append(
                    "  | Parameter | Type | Required | Description |"
                )
                lines.append("  | --- | --- | :---: | --- |")
                req_top = required_fields(schema)
                for pname, pinfo in relevant:
                    lines.append(
                        "  | `{n}` | `{t}` | {r} | {d} |".format(
                            n=md_escape_cell(pname),
                            t=md_escape_cell(schema_type(pinfo)),
                            r=md_bool(pname in req_top),
                            d=md_escape_cell(pinfo.get("description") or "—"),
                        )
                    )
                lines.append("")
    return "\n".join(lines)


_ACTION_LINE_RE = re.compile(r"^\s*-\s*([A-Za-z0-9_]+)\s*[:\u2014-]\s*(.+)$")


def _split_action_descriptions(text: str, enum_values: list[str]) -> dict[str, str]:
    """Best-effort split of the action enum description into per-action entries.

    Handles the common pattern used in the codebase::

        - add_items: add one or more entries to a collection ...
        - del_item: remove an entry ...
    """
    out: dict[str, str] = {}
    for line in text.splitlines():
        m = _ACTION_LINE_RE.match(line)
        if m:
            key = m.group(1).strip()
            desc = m.group(2).strip()
            if key in enum_values:
                out[key] = desc
    return out


def _params_for_action(
    props: dict, action_value: str, action_desc: str
) -> list[tuple[str, dict]]:
    """Heuristic: list params likely relevant to a given action.

    We look for property descriptions that mention the action name; if no
    matches are found we fall back to ALL non-action top-level parameters
    (better to over-show than under-show in `medium` depth).
    """
    relevant: list[tuple[str, dict]] = []
    for name, info in props.items():
        if name == "action":
            continue
        if not isinstance(info, dict):
            continue
        desc = (info.get("description") or "").lower()
        if action_value.lower() in desc:
            relevant.append((name, info))
    if not relevant:
        relevant = [
            (n, i) for n, i in props.items() if n != "action" and isinstance(i, dict)
        ]
    return relevant


def render_permissions(group: ToolGroup) -> str:
    rows = ["| Tool | Permissions |", "| --- | --- |"]
    for t in group.tools:
        perms = ", ".join(f"`{p}`" for p in t.permissions) or "—"
        rows.append(f"| `{t.name}` | {perms} |")
    return "\n".join(rows)


def render_metadata(group: ToolGroup) -> str:
    rows = [
        "| Tool | Version | Rate limit/min | Timeout (s) | Circuit breaker | Background | Multi-config |",
        "| --- | --- | ---: | ---: | :---: | :---: | :---: |",
    ]
    for t in group.tools:
        bg = "always" if t.always_background else (
            f">{t.background_threshold_seconds}s" if t.background_threshold_seconds else "—"
        )
        rows.append(
            "| `{n}` | `{v}` | {rl} | {to} | {cb} | {bg} | {mc} |".format(
                n=t.name,
                v=t.version,
                rl=t.rate_limit_per_minute,
                to=t.timeout_seconds,
                cb=md_bool(t.use_circuit_breaker),
                bg=bg,
                mc=md_bool(t.supports_multiple_configs),
            )
        )
    return "\n".join(rows)


def render_source_files(group: ToolGroup) -> str:
    seen: set[str] = set()
    items: list[str] = []
    for t in group.tools:
        if t.source_rel and t.source_rel not in seen:
            seen.add(t.source_rel)
            items.append(f"- {md_link(t.source_rel)}")
    return "\n".join(items) or "—"


# ──────────────────────────────────────────────────────────────────────
# Per-group document
# ──────────────────────────────────────────────────────────────────────


def render_group_doc(group: ToolGroup, depth: str) -> str:
    parts: list[str] = []
    parts.append(AUTOGEN_BANNER)
    parts.append(f"# {group.display_title}\n")

    overview = render_overview(group)
    parts.append("## Overview\n\n" + overview + "\n")

    if group.is_family:
        parts.append("## Tools in this group\n\n" + render_tools_table(group) + "\n")
    else:
        parts.append("## Tool\n\n" + render_tools_table(group) + "\n")

    # Configuration block — shared across the family or per the singleton.
    has_any_config = any(t.has_config for t in group.tools)
    if has_any_config:
        parts.append("## Configuration\n")

        notes: list[str] = []
        notes.append(
            "The JSON below goes into the **configtool model** in the web UI "
            "(per organisation; can also be scoped to a department)."
        )
        if any(t.supports_multiple_configs for t in group.tools):
            notes.append(
                "**Multiple profiles supported** — you may create more than one "
                "config row per organisation, each with a distinct `profile_id`. "
                "The agent picks one via the `config_profile` parameter at call time. "
                "State, rate limits and circuit-breaker counters are isolated per profile."
            )
        if any(
            (p.get("sensitive") for p in schema_properties(t.config_schema).values())
            for t in group.tools
        ):
            notes.append(
                "**Sensitive fields** (api keys / passwords / tokens) are *omitted* "
                "from the JSON below — set them via environment variables (see the "
                "_Environment variables_ table) or directly in the encrypted DB row "
                "from the web UI."
            )
        for note in notes:
            parts.append(f"> {note}\n")

        if group.is_family and group.namespace:
            ns_props, ns_required, ns_defaults = merge_schemas(group.tools)
        else:
            t = group.tools[0]
            ns_props = schema_properties(t.config_schema)
            ns_required = required_fields(t.config_schema)
            ns_defaults = dict(t.config_defaults)

        skeleton = render_config_skeleton(ns_props, ns_required, ns_defaults)
        example = render_config_example(ns_props, ns_defaults)
        parts.append("### Empty configtool template (required fields only)\n")
        parts.append("```json\n" + skeleton + "\n```\n")
        parts.append("### Example configtool model\n")
        parts.append("```json\n" + example + "\n```\n")
        if ns_props:
            parts.append("### Field reference\n")
            parts.append(render_field_reference(ns_props, ns_required, ns_defaults) + "\n")

    # Environment variables.
    parts.append("## Environment variables\n")
    parts.append(
        "The variables below are derived automatically from each tool's "
        "`config_schema`. Set them in your `.env` (or via your secrets backend) "
        "to seed defaults for every organisation. **Per-org DB config takes "
        "precedence over env vars.**\n"
    )
    parts.append(render_env_table(group))
    loose = render_loose_env_table(group)
    if loose:
        parts.append(loose)
    parts.append("")

    # Operations / actions.
    op_blocks: list[str] = []
    for t in group.tools:
        block = render_actions_section(t, depth)
        if block:
            op_blocks.append(f"### `{t.name}`\n\n{block}")
    if op_blocks:
        parts.append("## Operations\n")
        parts.append("\n\n".join(op_blocks) + "\n")

    # Permissions + Operational metadata.
    parts.append("## Permissions required\n\n" + render_permissions(group) + "\n")
    parts.append("## Operational metadata\n\n" + render_metadata(group) + "\n")
    parts.append("## Source files\n\n" + render_source_files(group) + "\n")

    return "\n".join(parts).rstrip() + "\n"


# ──────────────────────────────────────────────────────────────────────
# Index page
# ──────────────────────────────────────────────────────────────────────


def render_index(groups: list[ToolGroup], paths: dict[str, Path], output_dir: Path) -> str:
    parts: list[str] = []
    parts.append(AUTOGEN_BANNER)
    parts.append("# MCP Tools — Operator Reference\n")
    parts.append(textwrap.dedent("""\
        This index lists every MCP tool available in the running server,
        grouped by source category. Each linked page is auto-generated from
        the tool's Python source — see the **Source files** section at the
        bottom of every page to find the canonical definitions.

        **How configuration works:**

        1. Tools are configured at the *organisation* level (and optionally
           at the *department* level) via the **configtool model** in the
           web UI. The JSON shape of each model is documented on the tool's
           page under **Configuration**.
        2. Default values can also be set via environment variables in the
           backend's `.env`. The exact variable names are derived from each
           tool's schema and listed under **Environment variables** on each
           page; a consolidated dump lives in
           [`.env.tools.example`](../.env.tools.example) at the repo root.
        3. **Sensitive values** (API keys, passwords, tokens) should be set
           via env vars or directly in the encrypted DB row — *never*
           inlined in the JSON.
        4. Tools marked **multi-config** support several profiles per org
           with a distinct `profile_id` each.

        See [`docs/dev/TOOLS.md`](../dev/TOOLS.md) for the underlying
        framework (audience: developers).
    """))

    # Bucket by category.
    by_category: dict[str, list[ToolGroup]] = {}
    for g in groups:
        cat = g.tools[0].category if g.tools else "general"
        by_category.setdefault(cat, []).append(g)

    for category in sorted(by_category.keys()):
        parts.append(f"## {category}\n")
        rows = [
            "| Group / Tool | Tools | Permissions | Approval | Config | Multi-cfg | Page |",
            "| --- | ---: | --- | :---: | :---: | :---: | --- |",
        ]
        cat_groups = sorted(by_category[category], key=lambda g: g.group_id)
        for g in cat_groups:
            page = paths.get(g.group_id)
            if page is None:
                continue
            try:
                rel_link = str(page.relative_to(output_dir))
            except ValueError:
                rel_link = page.name
            tool_count = len(g.tools)
            perms = sorted({p for t in g.tools for p in t.permissions})
            perms_str = ", ".join(f"`{p}`" for p in perms) or "—"
            requires_appr = any(t.requires_approval for t in g.tools)
            has_config = any(t.has_config for t in g.tools)
            multi = any(t.supports_multiple_configs for t in g.tools)
            rows.append(
                "| `{gid}` | {n} | {perms} | {appr} | {cfg} | {mc} | [{rel}]({rel}) |".format(
                    gid=g.group_id,
                    n=tool_count,
                    perms=md_escape_cell(perms_str),
                    appr=md_bool(requires_appr),
                    cfg=md_bool(has_config),
                    mc=md_bool(multi),
                    rel=rel_link,
                )
            )
        parts.append("\n".join(rows) + "\n")

    return "\n".join(parts).rstrip() + "\n"


# ──────────────────────────────────────────────────────────────────────
# .env.tools.example
# ──────────────────────────────────────────────────────────────────────


def render_env_file(groups: list[ToolGroup]) -> str:
    out: list[str] = [ENV_FILE_BANNER, ""]
    for group in groups:
        if not any(t.has_config for t in group.tools):
            continue

        title = group.display_title
        out.append(f"# === {title} ===")
        out.append("")

        # Shared (namespace) block when applicable.
        namespace_fields: set[str] = set()
        if group.namespace and group.is_family:
            ns_props, _, ns_defaults = merge_schemas(group.tools)
            namespace_fields = set(ns_props.keys())
            for fname in sorted(ns_props.keys()):
                finfo = ns_props[fname]
                var = env_var_name(group.namespace, fname)
                desc = finfo.get("description")
                if desc:
                    out.append(f"# {desc}")
                if finfo.get("sensitive"):
                    out.append("# sensitive: store securely (do NOT commit real values)")
                    out.append(f"{var}=__SET_ME__")
                else:
                    default = field_default(ns_props, ns_defaults, fname)
                    out.append(f"{var}={_env_value_repr(default)}")
                out.append("")

        # Per-tool overrides — only fields NOT covered by the shared block.
        for t in group.tools:
            if t.config_namespace and t.config_namespace == t.name:
                continue
            props = schema_properties(t.config_schema)
            if not props and not t.config_defaults:
                continue
            scope = t.name
            block_added = False
            for fname in sorted(props.keys() | t.config_defaults.keys()):
                if fname in namespace_fields:
                    continue
                finfo = props.get(fname, {})
                var = env_var_name(scope, fname)
                if not block_added:
                    out.append(f"# --- override: {t.name} ---")
                    block_added = True
                desc = finfo.get("description")
                if desc:
                    out.append(f"# {desc}")
                if finfo.get("sensitive"):
                    out.append("# sensitive: store securely (do NOT commit real values)")
                    out.append(f"{var}=__SET_ME__")
                else:
                    default = field_default(props, t.config_defaults, fname)
                    out.append(f"{var}={_env_value_repr(default)}")
                out.append("")

        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _env_value_repr(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (list, dict)):
        return json.dumps(value, ensure_ascii=False)
    return str(value)


# ──────────────────────────────────────────────────────────────────────
# IO helpers (idempotent writes + --check)
# ──────────────────────────────────────────────────────────────────────


def write_if_changed(path: Path, content: str, *, check_only: bool) -> bool:
    """Return True if content differs from disk (and write unless check_only)."""
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return False
    if not check_only:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return True


# ──────────────────────────────────────────────────────────────────────
# Main entry point
# ──────────────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate operator-facing Markdown docs for every MCP tool.",
    )
    parser.add_argument(
        "--actions-depth",
        choices=("brief", "medium"),
        default="brief",
        help="How much detail to render for action-driven tools (default: brief).",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Where to write the .md files (default: {DEFAULT_OUTPUT_DIR.relative_to(ROOT)}).",
    )
    parser.add_argument(
        "--env-file",
        type=Path,
        default=DEFAULT_ENV_FILE,
        help=f"Where to write the consolidated env file (default: {DEFAULT_ENV_FILE.relative_to(ROOT)}).",
    )
    parser.add_argument(
        "--only",
        type=str,
        default=None,
        help="Restrict generation to tools whose name matches this regex (debug).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Dry-run: exit 1 if any output would change. Useful for CI guards.",
    )
    args = parser.parse_args()

    print("Discovering tools …")
    classes = discover_tools()
    if not classes:
        print("ERROR: No tools discovered.", file=sys.stderr)
        return 2

    only_re: Optional[re.Pattern[str]] = re.compile(args.only) if args.only else None

    tool_infos: list[ToolInfo] = []
    for tool_cls in classes.values():
        try:
            info = ToolInfo.from_class(tool_cls)
        except Exception as exc:
            print(f"  [skip] {tool_cls.__name__}: {exc}")
            continue
        if not info.available:
            continue
        # Restrict to the built-in package (custom tools are out of scope for v1).
        if not info.source_rel.startswith("src/mcp_server/tools/"):
            continue
        if only_re and not only_re.search(info.name):
            continue
        tool_infos.append(info)

    tool_infos.sort(key=lambda t: t.name)
    groups = group_tools(tool_infos)
    print(f"  → {len(tool_infos)} tools across {len(groups)} groups.")

    # Compute output paths first (used by index too).
    paths: dict[str, Path] = {}
    for group in groups:
        paths[group.group_id] = output_path_for(group, args.output_dir)

    changed: list[Path] = []

    # Per-group docs.
    for group in groups:
        target = paths[group.group_id]
        content = render_group_doc(group, args.actions_depth)
        if write_if_changed(target, content, check_only=args.check):
            changed.append(target)

    # Index page.
    index_path = args.output_dir / "README.md"
    index_content = render_index(groups, paths, args.output_dir)
    if write_if_changed(index_path, index_content, check_only=args.check):
        changed.append(index_path)

    # .env.tools.example
    env_content = render_env_file(groups)
    if write_if_changed(args.env_file, env_content, check_only=args.check):
        changed.append(args.env_file)

    if args.check:
        if changed:
            print("CHECK FAILED — the following files would change:")
            for p in changed:
                try:
                    rel = p.relative_to(ROOT)
                except ValueError:
                    rel = p
                print(f"  - {rel}")
            return 1
        print("OK — generated docs are in sync with the codebase.")
        return 0

    if changed:
        print(f"Wrote / updated {len(changed)} file(s):")
        for p in changed:
            try:
                rel = p.relative_to(ROOT)
            except ValueError:
                rel = p
            print(f"  - {rel}")
    else:
        print("No changes — docs already in sync.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
