#!/usr/bin/env python3
"""Generate operator-facing Markdown documentation for every gSage channel.

The generator is the channel-side analogue of
``scripts/generate_tools_docs.py``: it walks every ``channel_spec`` module
under ``src/`` (currently telegram, teams, email) and renders one
Markdown file per channel under ``docs/channels/`` plus a consolidated
``docs/channels/README.md`` index and a ``.env.channels.example`` file
at the repository root.

The source of truth is the ``CHANNEL_SPEC`` constant inside each
channel's ``channel_spec.py``. The generated files are idempotent and
must never be hand-edited.

Usage::

    python scripts/generate_channels_docs.py
    python scripts/generate_channels_docs.py --check    # exit 1 on diff
    python scripts/generate_channels_docs.py --only telegram

Run ``--check`` in CI to guard against drift between the code and the
generated docs.
"""

from __future__ import annotations

import argparse
import importlib
import re
import sys
import textwrap
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from scripts._doc_helpers import (  # noqa: E402
    env_value_repr,
    md_bool,
    md_escape_cell,
    md_link,
    render_config_example,
    render_config_skeleton,
    render_field_reference,
    required_fields,
    scan_loose_env_vars,
    schema_properties,
    write_if_changed,
)
from src.shared.channels import ChannelSpec  # noqa: E402

DEFAULT_OUTPUT_DIR = ROOT / "docs" / "channels"
DEFAULT_ENV_FILE = ROOT / ".env.channels.example"
SRC_DIR = ROOT / "src"

AUTOGEN_BANNER = (
    "<!-- AUTO-GENERATED by scripts/generate_channels_docs.py — do not edit manually. -->\n"
    "<!-- Source of truth: each channel's ``channel_spec.py`` listed at the bottom. -->\n"
)

ENV_FILE_BANNER = (
    "# AUTO-GENERATED by scripts/generate_channels_docs.py — do not edit manually.\n"
    "# Derived from each channel's `CHANNEL_SPEC.env_vars`.\n"
    "# Fill in the values that apply to your deployment in your real `.env`.\n"
    "#\n"
    "# Sensitive fields are emitted with a placeholder `__SET_ME__`. NEVER commit\n"
    "# real secrets to git — use `.env`, a secret manager, or the encrypted DB row.\n"
    "#\n"
    "# Per-organisation settings (bot tokens, IMAP credentials, etc.) are NOT\n"
    "# listed here — they live in the database and are managed via\n"
    "# `python -m ops_cli channels …`.\n"
    "#\n"
)


# ──────────────────────────────────────────────────────────────────────
# Discovery
# ──────────────────────────────────────────────────────────────────────


def discover_channel_specs() -> list[tuple[str, ChannelSpec, str]]:
    """Return ``(module_name, spec, source_rel)`` for every ``channel_spec`` module under ``src/``."""
    found: list[tuple[str, ChannelSpec, str]] = []

    # Walk the top-level packages under ``src/`` only — depth 1 is enough.
    for pkg_dir in sorted(p for p in SRC_DIR.iterdir() if p.is_dir()):
        candidate = pkg_dir / "channel_spec.py"
        if not candidate.exists():
            continue
        module_name = f"src.{pkg_dir.name}.channel_spec"
        try:
            module = importlib.import_module(module_name)
        except Exception as exc:  # pragma: no cover — surfaced to operator
            print(f"  [skip] {module_name}: {exc}", file=sys.stderr)
            continue
        spec = getattr(module, "CHANNEL_SPEC", None)
        if not isinstance(spec, ChannelSpec):
            continue
        try:
            source_rel = str(Path(module.__file__).resolve().relative_to(ROOT))  # type: ignore[arg-type]
        except (TypeError, ValueError):
            source_rel = module_name.replace(".", "/") + ".py"
        found.append((module_name, spec, source_rel))

    found.sort(key=lambda x: x[1].interface)
    return found


# ──────────────────────────────────────────────────────────────────────
# Markdown rendering
# ──────────────────────────────────────────────────────────────────────


def _channel_title(spec: ChannelSpec) -> str:
    pretty = spec.interface.replace("_", " ").title()
    return f"{pretty} Channel"


def render_overview(spec: ChannelSpec) -> str:
    parts = [spec.summary.strip()]
    if spec.description and spec.description.strip() != spec.summary.strip():
        parts.append("")
        parts.append(spec.description.strip())
    return "\n".join(parts)


def render_facts_table(spec: ChannelSpec) -> str:
    rows = ["| Field | Value |", "| --- | --- |"]
    rows.append(f"| Interface key | `{spec.interface}` |")
    rows.append(f"| Config storage | `{spec.config_storage}` |")
    if spec.cli_module:
        rows.append(f"| CLI module | `{spec.cli_module}` |")
    if spec.worker_modules:
        wm = ", ".join(f"`{m}`" for m in spec.worker_modules)
        rows.append(f"| Worker modules | {wm} |")
    if spec.webhook_paths:
        wp = ", ".join(f"`{p}`" for p in spec.webhook_paths)
        rows.append(f"| Webhook paths | {wp} |")
    return "\n".join(rows)


def render_interface_config_section(spec: ChannelSpec) -> str:
    schema = spec.interface_config_schema
    if not schema:
        return (
            "_This channel uses a dedicated relational table for its "
            "per-organisation configuration. See the **Source files** "
            "section for the model definition._"
        )
    props = schema_properties(schema)
    required = required_fields(schema)
    defaults = dict(spec.interface_config_defaults)

    parts: list[str] = []
    note = (
        "The JSON below describes the per-organisation configuration. "
    )
    if spec.config_storage == "interface_profile.interface_config":
        note += (
            "It is stored in `GSageInterfaceProfile.interface_config` "
            "(JSONB column) and managed via `python -m ops_cli channels "
            f"{spec.interface} …`."
        )
    elif spec.config_storage == "email_account_table":
        note += (
            "Each entry corresponds to one row in the `GSageEmailAccount` "
            "table; the columns map 1:1 to the fields below."
        )
    else:
        note += f"Storage backend: `{spec.config_storage}`."
    parts.append(f"> {note}\n")

    if any(props.get(f, {}).get("sensitive") for f in props):
        if spec.config_storage == "interface_profile.interface_config":
            parts.append(
                "> **Sensitive fields** (passwords, tokens, secrets) are "
                "currently stored *as-is* in the JSONB column — gSage does "
                "not yet encrypt them at rest. Treat the database as a "
                "secret store and provide values through the CLI's "
                "`--*-stdin` flags so they never appear in argv or shell "
                "history.\n"
            )
        else:
            parts.append(
                "> **Sensitive fields** (passwords, tokens, secrets) are "
                "encrypted at rest by the storage backend, but the JSON "
                "below shows the logical shape — supply real values "
                "through the CLI's `--*-stdin` flags.\n"
            )

    parts.append("### Empty template (required fields only)\n")
    parts.append(
        "```json\n" + render_config_skeleton(props, required, defaults) + "\n```\n"
    )
    parts.append("### Example payload\n")
    parts.append(
        "```json\n" + render_config_example(props, defaults) + "\n```\n"
    )
    parts.append("### Field reference\n")
    parts.append(render_field_reference(props, required, defaults) + "\n")
    return "\n".join(parts)


def render_env_table(spec: ChannelSpec) -> str:
    if not spec.env_vars:
        return "_No cluster-wide environment variables._"
    rows = [
        "| Variable | Type | Default | Sensitive | Description |",
        "| --- | --- | --- | :---: | --- |",
    ]
    for ev in sorted(spec.env_vars, key=lambda e: e.name):
        if ev.sensitive or ev.default is None:
            d_repr = "—"
        else:
            d_repr = f"`{env_value_repr(ev.default)}`"
        rows.append(
            "| `{n}` | `{t}` | {d} | {s} | {desc} |".format(
                n=ev.name,
                t=md_escape_cell(ev.type),
                d=md_escape_cell(d_repr),
                s=md_bool(ev.sensitive),
                desc=md_escape_cell(ev.description),
            )
        )
    return "\n".join(rows)


def render_loose_env_table(spec: ChannelSpec) -> str:
    sources = [ROOT / s for s in spec.source_files]
    sources = [p for p in sources if p.exists()]
    declared = {ev.name for ev in spec.env_vars}
    pairs = scan_loose_env_vars(sources)
    pairs = [(n, d) for (n, d) in pairs if n not in declared]
    if not pairs:
        return ""
    rows = [
        "",
        "**Other environment variables** (read directly from the source — "
        "not declared in `CHANNEL_SPEC.env_vars`):",
        "",
        "| Variable | Default in code |",
        "| --- | --- |",
    ]
    for name, default in pairs:
        d_repr = "—" if default is None else f"`{default}`"
        rows.append(f"| `{name}` | {d_repr} |")
    return "\n".join(rows)


def render_cli_examples(spec: ChannelSpec) -> str:
    if not spec.cli_examples:
        return "_No CLI examples declared._"
    parts: list[str] = []
    for ex in spec.cli_examples:
        parts.append(f"**{ex.title}**\n")
        parts.append("```bash\n" + ex.command.rstrip() + "\n```\n")
    return "\n".join(parts)


def render_prerequisites(spec: ChannelSpec) -> str:
    if not spec.prerequisites:
        return "_(none documented)_"
    return "\n".join(f"- {p}" for p in spec.prerequisites)


def render_source_files(spec: ChannelSpec, spec_source: str) -> str:
    seen: list[str] = []
    if spec_source and spec_source not in seen:
        seen.append(spec_source)
    for s in spec.source_files:
        if s not in seen:
            seen.append(s)
    return "\n".join(f"- {md_link(s)}" for s in seen) or "—"


def render_channel_doc(spec: ChannelSpec, spec_source: str) -> str:
    parts: list[str] = []
    parts.append(AUTOGEN_BANNER)
    parts.append(f"# {_channel_title(spec)}\n")
    parts.append("## Overview\n\n" + render_overview(spec) + "\n")
    parts.append("## Quick facts\n\n" + render_facts_table(spec) + "\n")
    parts.append("## Per-organisation configuration\n\n"
                 + render_interface_config_section(spec) + "\n")
    parts.append("## Environment variables\n")
    parts.append(
        "These cluster-wide variables seed the channel's runtime defaults. "
        "Set them in your `.env` (or via your secrets backend) before "
        "starting the worker. **Per-org configuration** (see the previous "
        "section) takes precedence at runtime.\n"
    )
    parts.append(render_env_table(spec))
    loose = render_loose_env_table(spec)
    if loose:
        parts.append(loose)
    parts.append("")
    parts.append("## CLI usage\n\n" + render_cli_examples(spec) + "\n")
    parts.append("## Prerequisites\n\n" + render_prerequisites(spec) + "\n")
    parts.append("## Source files\n\n" + render_source_files(spec, spec_source) + "\n")
    return "\n".join(parts).rstrip() + "\n"


# ──────────────────────────────────────────────────────────────────────
# Index page
# ──────────────────────────────────────────────────────────────────────


def render_index(entries: list[tuple[ChannelSpec, Path]], output_dir: Path) -> str:
    parts: list[str] = []
    parts.append(AUTOGEN_BANNER)
    parts.append("# gSage Channels — Operator Reference\n")
    parts.append(textwrap.dedent("""\
        Each channel lets users talk to the SOC over an external transport
        (Telegram, Microsoft Teams, e-mail). The pages below document the
        configuration surface that an operator must provision **before**
        the channel starts working — both the per-organisation rows that
        live in the database and the cluster-wide environment variables
        consumed by the worker.

        **How configuration works:**

        1. **Per-organisation** settings (bot tokens, mailbox credentials,
           Azure App secrets, …) are stored in the database — either in
           `GSageInterfaceProfile.interface_config` or in the
           `GSageEmailAccount` table. Manage them via:

           ```bash
           python -m ops_cli channels <interface> …
           ```

        2. **Cluster-wide** runtime knobs (rate limits, polling
           intervals, default sender addresses, …) live in
           environment variables. A consolidated dump is available at
           [`.env.channels.example`](../.env.channels.example).

        3. The `web` channel (HTTP chat) is intentionally not listed
           here — its configuration is part of the backend API and is
           covered separately.

        Architectural background:
        [`docs-local/architecture/15-INTERFACE-CHANNEL-ARCHITECTURE.md`](../../docs-local/architecture/15-INTERFACE-CHANNEL-ARCHITECTURE.md).
    """))

    rows = [
        "| Channel | Summary | Storage | Webhook | CLI |",
        "| --- | --- | --- | :---: | :---: |",
    ]
    for spec, page in entries:
        try:
            rel_link = str(page.relative_to(output_dir))
        except ValueError:
            rel_link = page.name
        webhook = "✓" if spec.webhook_paths else "—"
        cli = "✓" if spec.cli_module else "—"
        rows.append(
            "| [`{i}`]({rel}) | {summary} | `{store}` | {wh} | {cli} |".format(
                i=spec.interface,
                rel=rel_link,
                summary=md_escape_cell(spec.summary),
                store=spec.config_storage,
                wh=webhook,
                cli=cli,
            )
        )
    parts.append("\n".join(rows) + "\n")
    return "\n".join(parts).rstrip() + "\n"


# ──────────────────────────────────────────────────────────────────────
# .env.channels.example
# ──────────────────────────────────────────────────────────────────────


def render_env_file(specs: list[ChannelSpec]) -> str:
    out: list[str] = [ENV_FILE_BANNER, ""]
    for spec in specs:
        if not spec.env_vars:
            continue
        out.append(f"# === {_channel_title(spec)} ===")
        out.append("")
        for ev in sorted(spec.env_vars, key=lambda e: e.name):
            out.append(f"# {ev.description}")
            if ev.sensitive:
                out.append("# sensitive: store securely (do NOT commit real values)")
                out.append(f"{ev.name}=__SET_ME__")
            else:
                out.append(f"{ev.name}={env_value_repr(ev.default)}")
            out.append("")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


# ──────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate operator-facing Markdown docs for every channel.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Where to write the .md files (default: {DEFAULT_OUTPUT_DIR.relative_to(ROOT)}).",
    )
    parser.add_argument(
        "--env-file",
        type=Path,
        default=DEFAULT_ENV_FILE,
        help=f"Where to write the consolidated env file (default: {DEFAULT_ENV_FILE.relative_to(ROOT)}).",
    )
    parser.add_argument(
        "--only",
        type=str,
        default=None,
        help="Restrict generation to channels whose interface matches this regex (debug).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Dry-run: exit 1 if any output would change. Useful for CI guards.",
    )
    args = parser.parse_args()

    print("Discovering channel specs …")
    discovered = discover_channel_specs()
    if not discovered:
        print("ERROR: No channel specs discovered.", file=sys.stderr)
        return 2

    only_re: Optional[re.Pattern[str]] = re.compile(args.only) if args.only else None
    selected: list[tuple[str, ChannelSpec, str]] = []
    for module_name, spec, source_rel in discovered:
        if only_re and not only_re.search(spec.interface):
            continue
        selected.append((module_name, spec, source_rel))

    print(f"  → {len(selected)} channel(s).")

    changed: list[Path] = []
    index_entries: list[tuple[ChannelSpec, Path]] = []

    # Per-channel docs.
    for _module_name, spec, source_rel in selected:
        target = args.output_dir / f"{spec.interface}.md"
        content = render_channel_doc(spec, source_rel)
        if write_if_changed(target, content, check_only=args.check):
            changed.append(target)
        index_entries.append((spec, target))

    # Index page (always reflects all selected channels — never partial when --only is used,
    # callers should re-run without --only for a full index).
    index_path = args.output_dir / "README.md"
    index_content = render_index(index_entries, args.output_dir)
    if write_if_changed(index_path, index_content, check_only=args.check):
        changed.append(index_path)

    # .env.channels.example
    env_content = render_env_file([s for _m, s, _r in selected])
    if write_if_changed(args.env_file, env_content, check_only=args.check):
        changed.append(args.env_file)

    if args.check:
        if changed:
            print("CHECK FAILED — the following files would change:")
            for p in changed:
                try:
                    rel = p.relative_to(ROOT)
                except ValueError:
                    rel = p
                print(f"  - {rel}")
            return 1
        print("OK — generated docs are in sync with the codebase.")
        return 0

    if changed:
        print(f"Wrote / updated {len(changed)} file(s):")
        for p in changed:
            try:
                rel = p.relative_to(ROOT)
            except ValueError:
                rel = p
            print(f"  - {rel}")
    else:
        print("No changes — docs already in sync.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
